### ISSUE TITLE
Refactor CamViewState To Be More Extensible

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#147]
Currently, CamViewStates are limited to a predefined set of actions that can be performed on selected or hovered objects. Also, the code has become quite cluttered with specific checks for individual actions. This is all not very nice. See what can be done to improve the situation.
- Have a distinct class for each action that can be performed, similar to this? https://github.com/BraveSirAndrew/duality/commit/ab46ccd9119e92ee68db639a3b35ee0bacbda6d3
- Refactor SelObj itself as well?
- Ideally, it would be possible for an editor plugin to just add a new action to an existing state.
- Also, view this in context of the [RigidBody Editor Improvements](https://github.com/AdamsLair/duality/issues/54) to come.

**Comment by ilexp** [comment]
In the wake of the recent works in a Tilemaps plugin, CamViewState has been refactored to allow a more versatile set of different implementations with less unused overhead. Most of the functionality mentioned here has been moved to the abstract `ObjectEditorCamViewState` subclass of `CamViewState`.

When approaching this, the new `TilemapEditorCamViewState` can serve as a role model for this, since it defines all of its tools in a modular war as distinct classes. They are discovered using Duality's plugin / reflection API and are extensible by third-party plugins easily.

**Comment by ilexp** [comment]
Closing this issue, as it seems to be stale, without clear direction, and open ended.
