### ISSUE TITLE
Add a "Select Object" Button next to Reference Editors

### ISSUE THREAD

**Issue by AdamsLair** [AdamsLair/duality#150]
- DragDrop is neat, but sometimes it just takes longer to search for the object in Scene or Project View than to simply open up a new window, enter a search term and select it.
- This button might replace the existing "highlight" button, because there's no space left. Maybe make the highlight button "optional", so that it only shows up when there's enough space?
- Open up a new window
  - Contains a flat list of applicable objects
  - Search field, focused by default
  - List is sorted by "match score" with the search field contents plus "most recently used score"
  - Hitting the return key on the reference property editor will open up the window. Hitting the return key in the window will select the topmost list item and accept it immediately. No mouse interaction required!
- Refactor the Create Object dialog to be actually a special case of this one, just with Types as "objects".

**Comment by BobGneu** [comment]
Per the conversations with Adam and the crew in Discord, the request is to replace the highlight button here: 

![image](https://user-images.githubusercontent.com/857751/33594275-26174d88-d948-11e7-91ad-4f2e7936804e.png)

The replacement button should prompt the user with a filtered list of valid objects, allowing them to select from the elements in their project hierarchy. The selection box should 

* provide filters for relevance, recent usage. 
* It should only include relevant types in the listing. 
* should be the focus when the window is displayed
* should highlight the currently selected element when displayed. 
* should adhere to the color scheme of the application thus far
* should be modal

As it is, it looks like we have room for another button if we wish, so we can keep the highlight option if we want. 

As for an icon, we can use a funnel or similar to emphasize the filtering process. 

Due to the suggestion that we have a relevance, there may be a dependency to implement, although we can use things like word distance or a similar algorithm for the search implementation. In either case, configuration may be beneficial, even if not bubbled up to the user directly. I will note possible configuration options as this task comes together.

**Comment by ilexp** [comment]
Very good analysis. Don't have much to add, just some ideas I got while reading your post:

> should be modal

Yep. Alternatively, should that feel too "limiting", we could explore a "close on lose focus" non-modal dialog type, but let's try the modal version first.

> As it is, it looks like we have room for another button if we wish, so we can keep the highlight option if we want.

Actually, I think we should remove the highlight button, but keep the functionality when clicking on the main / preview area of the reference editor. It is currently used for display only, but has no interaction aside from being a dragdrop receiver - might as well trigger a highlight when clicking it in order to clear some space for more important buttons.

> As for an icon, we can use a funnel or similar to emphasize the filtering process.

A funnel sounds alright, but maybe also keep a lookout in case there's something more fitting in the iconset. Duality uses the [famfamfam silk](http://www.famfamfam.com/lab/icons/silk/) set for small icons and the [fatcow](http://www.fatcow.com/free-icons) set for big icons.

> Due to the suggestion that we have a relevance, there may be a dependency to implement, although we can use things like word distance or a similar algorithm for the search implementation.

For a first iteration, maybe just combine (name) filter match, recent usage and alphabetical orders to sort the display list, from first to last. I don't think we really need a complex relevance algorithm in an initial release - we can always improve later.

**Comment by BobGneu** [comment]
Referenced in chat, but want to replicate my question here in the interests of keeping all of the notes together. 

> the main / preview area of the reference editor. 

By this, I assume you are referring to the white text field that reads out the path for the asset/prefab, as in the image above. If so, it should be straight forward to address all of the above in the same ticket.

**Comment by BobGneu** [comment]
I looked at the control deeper and I see that double clicking that field has the highlight functionality you describe. I will not be modifying that behavior.

**Comment by ilexp** [comment]
> Referenced in chat, but want to replicate my question here in the interests of keeping all of the notes together.

Agreed. Issue discussions are the main place to discuss these things, we should keep the chat out of this for the main discussion.

> By this, I assume you are referring to the white text field that reads out the path for the asset/prefab, as in the image above. If so, it should be straight forward to address all of the above in the same ticket.

Yep, that's it.

> I looked at the control deeper and I see that double clicking that field has the highlight functionality you describe. I will not be modifying that behavior.

Oh, it does? Heh, didn't remember putting that in there. In that case, maybe just trigger it on a single-click instead to make it more discoverable.

**Comment by BobGneu** [comment]
Sure thing. Noted.

**Comment by BobGneu** [comment]
got the changes to switch the highlight behavior to single click from double in place last night. What do you think about having the double click on that field to be the same action as opening the asset selection form?

**Comment by ilexp** [comment]
> What do you think about having the double click on that field to be the same action as opening the asset selection form?

Sounds good 👍 If you get around to it, check "select object" as an alternative double click action to accompany the "highlight object" single click action to see which feels more intuitive.

**Comment by ilexp** [comment]
Just noticed in the network view that you seem to be basing your current work on `develop-3.0`? If that's correct, consider instead creating a new feature branch off of `master`, so we can release this as a v2.x update, rather than waiting for v3.0. Better to port the changes now than later.

**Comment by BobGneu** [comment]
Roger.

**Comment by BobGneu** [comment]
Restarted on Master. [PR#593](https://github.com/AdamsLair/duality/pull/593) is the current proposed solution to this issue.

**Comment by ilexp** [comment]
Sounds good! Let's proceed with the discussion and gradual review on the PR.

**Comment by ilexp** [comment]
Implemented by @BobGneu, binary release is on its way. Closing this.
