### ISSUE TITLE
Could not find an appropriate application to open the file

### ISSUE THREAD

**Issue by ProtectedMode** [AdamsLair/duality#165]
Sorry for opening issues so fast...

When trying to edit the source code by pressing the `Open Sourcecode` button, an error dialog appears giving the error in the title of this issue. There is nothing interesting in the two log files I know of.

Does Duality support VS 2013?

**Comment by ProtectedMode** [comment]
After downloading the example game package, I can open VS there, but not in a new Duality project.

**Comment by AdamsLair** [comment]
Duality emits VS2010 Express projects and solutions, but you can safely open and edit them with all newer versions of VS as well. You may need to tell Windows to open .sln files with the specific VS version you're using instead of the generic "Visual Studio Version Selector".

I'm aware that this is a little counter-intuitive on certain systems, but I didn't get around to address this so far. There is [an issue dealing with this](https://github.com/AdamsLair/duality/issues/33), in case you want to keep track.

> Sorry for opening issues so fast...

As long as you're not sure whether this is really a framework issue or just something on your system, [the forum](http://forum.adamslair.net) is a good place to talk about it first and find out. :)
