### ISSUE TITLE
Set default workspace directory

### ISSUE THREAD

**Issue by RockyTV** [AdamsLair/duality#172]
Maybe have something like Eclipse has, that sets the default workspace. Or something like Visual Studio.

**Comment by AdamsLair** [comment]
Duality doesn't have official support for multiple workspaces or editing projects and this is not planned to be changed in the near future - mainly because Duality has a very dynamic development and each project should be able to use "its own" version of Duality, so old projects don't break, but coexist peacefully with the newer ones.

There is, however, a somewhat unofficial support for this, because it's useful for plugin development. It is possible to run Duality with a different working directory than the one the binaries are located in. To do this, you can either write yourself a batch script to set the current directory to your workspace and then "remotely" run the Duality executables, or create a Windows shortcut to it and specify a different working directory in the properties dialog.

Hope this helps a little :)
