### ISSUE TITLE
Large world support

### ISSUE THREAD

**Issue by HeadClot** [AdamsLair/duality#258]
Hey,
I am working on a 2D project in Unreal 4 that is fairly big in terms of world size. I am looking to port it away from Unreal 4 due to the fact that 2D support is not all that good at the moment in terms of performance.

That said - I have been trying to get large world support working in Duality for a day or two now. No real progress on my end.

[This](http://xboxforums.create.msdn.com/forums/p/111091/663342.aspx#663342) should provide more context for what I want.

To sum it up:

![Image 1](http://www.xnafan.net/downloads/_tutorials/InfiniteWorld/infinite-worlds_01.png)

The world is broken up into a series of Chunks / sub levels.

![Image 2](http://www.xnafan.net/downloads/_tutorials/InfiniteWorld/infinite-worlds_02.png)

When a player loads or starts the game - It should load the map that the player is currently in and buffer the maps that are adjacent to the player. As well as unload any maps as needed.

![Image 3](http://www.xnafan.net/downloads/_tutorials/InfiniteWorld/infinite-worlds_03.png)

If the players view enters any adjacent level chunks then it should render them.

![Image 4](http://www.xnafan.net/downloads/_tutorials/InfiniteWorld/infinite-worlds_04.png)

The rest of this should be self explanatory.

This should all be handled from some form of GUI for ease of use for artists.

I am not sure how feasible this is at the moment for Duality but It is something that I would like to see and would contribute too as I learn more.

**Comment by ilexp** [comment]
> Hey,
I am working on a 2D project in Unreal 4 that is fairly big in terms of world size. I am looking to port it away from Unreal 4 due to the fact that 2D support is not all that good at the moment in terms of performance.

Hey! Good to hear you're considering Duality :)

> To sum it up:

So, the general idea I get here is splitting up your world into different sectors, and loading / unloading them as needed. This is a great idea for big game worlds, but also very specific: Most games won't need this, and the games that do likely need it in a very specialized form. Which is why I don't think this would be a good idea to be introduced into the core. It's also nothing that requires any core changes, so you might as well create a plugin that does what you need - or prototype it directly in your game plugin as you did so far.

I hope you understand why I'm closing this issue, but in any case don't read this as me thinking this is a bad idea - because it's not. I just don't think this would be a good match for the general-purpose Duality feature set, or something that I could provide on a generalized level for others to use without them having to rewrite half of it every time.

My suggestion would be to create a custom "Scene Management" Component that keeps track of the sectors and loads and unloads the appropriate Scenes that are associated with each sector. You can use a base Scene as an "aggregator" where the others get added to and removed from.

If you need help with this, feel free to create a new forum topic and discuss your progress with us :)

**Comment by HeadClot** [comment]
Hey @ilexp,

Yeah I think this would be better off as a plugin as well. Mainly to keep the core lean and fast. So I will try that approach first. [This](https://www.youtube.com/watch?v=orfhxY2PTr4) is what I am aiming for using duality for large world support. This is just to give you a better Idea of what I am aiming for.

Thanks for your time,

HeadClot
