### ISSUE TITLE
Keep the dragging of Rigidbodies between objects from adding the default circle

### ISSUE THREAD

**Issue by deanljohnson** [AdamsLair/duality#261]
Currently, if you drag a Rigidbody from one GameObject to another, it will add the default circle shape to the rigidbody. Steps to reproduce:

1. Create two empty GameObjects, A and B
2. Add a Rigidbody to object A
3. Replace the default circle collision shape with something else.
4. Drag and drop the Rigidbody and Transform from object A onto object B

Now if you look in the Rigidbody editor, you should see that it kept the shape we replaced the default shape with, but it re-added the default circle.

I'm assuming that this is because the Rigidbody is re-created rather than moved, and during it's construction the default circle is added. However, I also noticed that cloning a GameObject does not add back-in that default circle, so the functionality already exists somewhere to re-create the Rigidbody without adding that default circle.

**Comment by ilexp** [comment]
Thanks for reporting! This is probably a minor bug in editor-related code.

**Comment by deanljohnson** [comment]
I've tracked down the bug, but can't think of a good solution so I'm posting my findings here to see what other people think.

The problem occurs here:
https://github.com/AdamsLair/duality/blob/5f0f69127e09469c722e54f2d1dc2f6f816f9f2a/Duality/Components/Physics/RigidBody.cs#L1154

In the case of a drag-and-drop operation, OnInit is called with context set to AddToGameObject, and we are in the editor, so the RigidBody is assuming that it is a new RigidBody, which is not the case in a drag-and-drop operation.

At first I naively thought to check if the RigidBody's shape count was 0, but that'd cause the same bug if I was drag-and-dropping a RigidBody that I intended to have no shapes.

There could be a new InitContext, such as InitContext.Construction, but that clutters the InitContext enum even more, which just causes more problems for issue #136, so that's not a good fix. Perhaps the fix for this bug will stem from a fix to the InitContext issue.

We could add the default circle in the event handler for creating a new RigidBody. I haven't looked at that code yet so I'm not sure if that's going to provide a clean solution. Furthermore, I could see other Component's needing to know whether or not they are a completely new instance, so whatever solution is developed for this bug should address this issue for other Component's as well.

**Comment by ilexp** [comment]
Very good analysis of the problem! I would see the solution to be implemented within the editor, rather than the core itself, since this is actually an editor feature which (unfortunately) was previously implemented in the core.

One thing the editor could benefit from would be some kind of mechanism to perform additional initialization to newly created Components (and Resources!) beyond simply calling the constructor. This would make sense whenever something is created for the purpose of being set up for user editing.

One way to deal with this could be to introduce a new context for [EditorActions](https://github.com/AdamsLair/duality/blob/master/DualityEditor/Extensibility/EditorActions/EditorAction.cs#L36), allowing editor plugins to implement a custom user-editing setup action for select Component and Resource types. 

Since dragdrop is not creation, the code would not trigger in this specific case as expected.

**Comment by deanljohnson** [comment]
What if components had an EditorDefault property, which is used to clone components from when a new Component is created in the editor?

 Or to keep this from mixing editor code with core code, the editor can keep a lookup table of these defaults. Then any plugin developers can push their own defaults on to the lookup table to have their Components initialized from within the editor correctly.

Duality's built in components can have their defaults hard coded into the editor plugin.

**Comment by ilexp** [comment]
> Duality's built in components can have their defaults hard coded into the SceneView plugin.

I always try to follow the principle of not making a distinction between "official" plugins and third-party plugins, so whenever one of "my" plugins gets to have a feature, there should always be a way to access it from the outside as well. This doesn't always work, but I think you can see why I wouldn't want to choose that kind of hardcoding to solve the issue.

> What if components had an EditorDefault property, which is used to clone components from when a new Component is created in the editor?

So.. a static property that returns an already initialized instance of the Component / Resource, which will be used as a cloning source for new user-generated objects for editing?

That doesn't sound too bad. Now the main decision seems to be whether to use default data (your suggestion) or init code for default data (having some kind of custom init code as I described previously), as well as to whether or not to expose a core plugin way of providing either.

> A problem that I could see is what if the editor default for a Component needed to know about the GameObject it was being added to. For that, we would need the lookup table to be something like a Dictionary.

This case would seem to suggest a code-wise solution, rather than a default data solution. However, I'm not sure whether this case should be addressed at all, since the GameObject in question will always be in an "under construction" state that allows only limited insight into the context the new Component is created in. It may be better to think of the creation as an isolated process independent from context other than the purpose for which the object is created.

**Comment by deanljohnson** [comment]
I think I didn't explain my proposed solution very well... that and I've iterated upon my idea. Third-party plugins would have the ability to define editor only initializers for their components. I'll explain my solution in more detail in a second.

The reason I think it should be done within the editor and not backed by the core is that these initializers are only valid within the context of the editor. Without the editor, you have regular Component initialization which can be handled by the OnInit method.

Your point about the GameObject reference is spot-on, hadn't thought about it that way.

Now for a better run-down of my proposed solution:
Within the SceneView.Editor project, create a new static class ComponentInitializers, that looks roughly like this:

```csharp
    public static class ComponentInitializers
    {
        //The GameObject parameter isn't needed as you've said,
        // but I'm copying this from my current code
        private static readonly Dictionary<Type, Func<GameObject, Component>> cmpInitializers = new Dictionary<Type, Func<GameObject, Component>>();

        static ComponentInitializers()
        {
            cmpInitializers.Add(typeof(RigidBody), delegate (GameObject o)
            {
                RigidBody body = new RigidBody();
                body.AddShape(new CircleShapeInfo(128.0f, Vector2.Zero, 1.0f));
                return body;
            });
        }

        public static bool Add(Type cmpType, Func<GameObject, Component> initializer)
        {
            if (cmpInitializers.ContainsKey(cmpType))
            {
                return false;
            }

            cmpInitializers.Add(cmpType, initializer);

            return true;
        }

        public static bool Remove(Type cmpType)
        {
            return cmpInitializers.Remove(cmpType);
        }

        public static bool Contains(Type cmpType)
        {
            return cmpInitializers.ContainsKey(cmpType);
        }

        public static Func<GameObject, Component> Get(Type cmpType)
        {
            return cmpInitializers.ContainsKey(cmpType) 
                ? cmpInitializers[cmpType] 
                : null;
        }
    }
```

In the static constructor we define the functions that will build Duality's core Components for us, if they require special editor only handling. Then when creating new Components through the SceneView.CreateComponent() method we can check to see if there is a function defined for the type of Component. Third-party plugins would just have to reference the SceneView dll and call ComponentInitializers.Add() with their own functions.

I agree this is not a perfect solution because of the special case handling provided to the core components, but it seems to me like we can go two ways with this:

1) Muck up Duality's core to provide special cases for the editor
2) Muck up the editor to provide special cases for the core

The way I look at it, the editor already relies on the core, so number 2 isn't too bad, whereas number 1 forces a connection between two sections of code that doesn't have to be there. Number 1 is a two-way dependency between Core and Editor, number 2 is one way from Editor to Core.

I've sudo-implemented this already, and it seems to work great, but I am having a horrible time with referencing the ComponentInitializers class from my own projects when I try to create an initializer for my own components - VS is giving me a "does not exist in current context" error that is proving to be very hard to fix....

**Comment by deanljohnson** [comment]
After re-reading the discussion here I seem to have missed a point you've been mentioning. This shouldn't really be handled inside SceneView, and could easily be moved into the Daulity.Editor project. Don't know why I've been forcing it into SceneView.

**Comment by deanljohnson** [comment]
I've pushed my possible solution to my duality fork at:
https://github.com/deanljohnson/duality/tree/fix-rigidbody-dragging

I took the class I proposed up above and placed it in the DualityEditor project, removed the editior initialization code within RigidBody, and added a check for initialization functions within SceneView.CreateComponent. Everything works as it should for RigidBody, but I still need to check the other Duality Components for editor initialization code.

Using this from a third-party plugin is as simple as calling ComponentInitializers.Add. To use it from a game project, you have to create an editor plugin that references your GamePlugin.core and describes how to initialize your Components for editor use. While this isn't as user friendly as I had hoped, it is clear in it's intent - for editor-specific functionality, you need an editor plugin.

The reason this has to be done in an editor plugin is because a game projects CorePlugin is a portable project type, which keeps it from accessing the DualityEditor assembly. If this class was moved into the Duality assembly we wouldn't have this issue, but I still think that is needless mixing of editor and core functionality. To me it's a trade off between usability and maintainability. If others think it's better off in the Duality assembly, that's a very simple fix for me to make, but that makes this solution a little convoluted - might as well have the EditorDefault properties on Component's as I mentioned above.

**Comment by ilexp** [comment]
> The reason I think it should be done within the editor and not backed by the core is that these initializers are only valid within the context of the editor. Without the editor, you have regular Component initialization which can be handled by the OnInit method.

I agree completely. This should be implemented in the editor. 

There is, however, the already existing exception of the declarative core editor interface, which allows users to specify how certain types and members behave using core attributes without any dependency on the editor. A similar interface could theoretically used for specifying this behavior without an additional dependency - for the purpose of user convenience. 

I'm a bit wary of adding editor-specific code to the core though, so I'm leaning more towards the editor-only solution so far. I think we're mostly on the same page here.

> Now for a better run-down of my proposed solution:

Something like this was present a lot in the initial design of the editor: Static classes providing some kind of centralized functionality with Add methods for third-party plugins. I have since redesigned the editor to get rid of these patterns completely in favor of a declarative approach. Core plugins already work in a purely declarative way and I think that consistency is a good reason to aim for editor plugins taking a similar direction.

The [EditorActions](https://github.com/AdamsLair/duality/blob/master/DualityEditor/Extensibility/EditorActions/EditorAction.cs#L36) I've linked above are a good example for the declarative way: There is no central static class managing data with which plugins have to communicate. Instead, they define custom Types that implement a certain interface or base class. The editor then uses reflection to determine the full set of available Types and uses them as it sees fit. Instead of explicit communication and the problem of manual (and thus potentially faulty) initialization and disposal / add and remove, this approach works mostly behind the scenes. 

[Here](https://github.com/AdamsLair/duality/tree/master/DualityEditorPlugins/EditorBase/EditorActions) are some examples of implemented editor actions - they are not added anywhere, they're just defined and used automatically according to the interface / base class they implement.

Even though I am not sure whether EditorActions would be a proper fit for an editor-specific object init / setup mechanism, their API would be a match so far and the declarative idea behind it is one that I would prefer. It has yet to be determine whether the purpose of EditorActions matches the one of custom editor initializers closely enough to use them directly.

**Comment by deanljohnson** [comment]
I could see the EditorActions working and I would like to stick with current design decisions. I'll work on this via a separate branch on my fork and see how it comes out. What kept me away from the EditorAction approach was it's apparent complexity for this issue that seemed simple to me at first. Now as I've delved more into the problem I can see the possible benefit towards that approach. If I run into any glaring issues I'll post them here. Or, would you prefer me to submit a pull request sooner rather than later so that the PR can be used as a place to discuss this?

**Comment by ilexp** [comment]
Saw your PR - thanks! Will take a look once I get around to it and then get back to you with feedback :)

**Comment by ilexp** [comment]
PR merged and fixed.
