### ISSUE TITLE
Moving from animation loop to a static frame

### ISSUE THREAD

**Issue by toyners** [AdamsLair/duality#273]
I had a situation where I was changing from looping over the animation to showing the first frame only. My initial attempts failed but after some digging around in Duality I came up with this code:

  this.renderer = this.GameObj.GetComponent<AnimSpriteRenderer>();
  ...
  this.renderer.AnimTime = 0;
  this.renderer.AnimFirstFrame = 0; // reset to first animation frame.
  this.renderer.AnimLoopMode = AnimSpriteRenderer.LoopMode.FixedSingle;

Off the back of this [posting](http://forum.adamslair.net/viewtopic.php?f=4&t=695) it occurs to me that I'm not the only one to struggle with freezing animations. I wonder if a formal method could be added that will accomplish this. This new method (with method documentation) will help new users to freeze animations in an easy, intuitive manner. Probably not urgent but still would be nice to have.

**Comment by ilexp** [comment]
Essentially, these two lines should be enough:

```
this.renderer.AnimTime = 0;
this.renderer.AnimLoopMode = AnimSpriteRenderer.LoopMode.FixedSingle;
```

I'm not sure it would be _much_ of an improvement to introduce a method that does exactly this - seems short enough to me, and I don't want to clutter the API. 

Do you have something specific in mind?

**Comment by toyners** [comment]
For me it's not about the length of code required but more about having an easy-to-find way to achieve it. The above 3 lines took me a while to work out (I went digging in the code base to see what was happening during animation and figured out that `AnimTime` was a crucial player). This seems undesirable for such fundamental functionality. And unintuitive - I thought setting the mode and frame index would do it (and has you have shown I was wrong about needing the `AnimFirstFrame` :smiley: )

I guess something like:

```
    /// <summary>
    /// Sets the current frame and the mode to LoopMode.FixedSingle essentially freezing the animation.
    /// </summary>
    /// <param name="index">Index of frame to show.</param>
    public void SetFrame(Int32 index)
    {
      // Where the magic happens
    }
```

That's my pitch I guess. I have a fork of Duality so would be happy to put the code (and tests) together and present it to you. Even if you knock it back I could always use it in my games - if I use it a lot then I'll have the benefit of hard data (sorta) to show :smile:

**Comment by ilexp** [comment]
I'm not entirely convinced on this to be honest. Don't get me wrong though, I do appreciate your effort to improve Duality on this! 

The thing is that I'm a bit wary of introducing new API and stuff to the core when the same is already (and easily) possible with existing code. I agree that this might be an issue for new users, but then again, it should be possible to fix this on the documentation side, rather than with more code. Adding a few notes in existing XML comments of the API docs might already fix this.

I think that there might be some middle ground though:
```
public static class ExtMethodsAnimSpriteRenderer
{
    public static void SetFrame(this AnimSpriteRenderer renderer, int index)
    {
        // Magic
    }
}
```
If you implement the methods you intended as extension methods, you can put them in a Duality plugin and publicly release it as a package for everyone to use, including you. That way, you would... 

- ...not have the potential inconvenience of a custom Duality version that requires syncing, merging and maintenance.
- ...keep things modular.
- ...be able to publish it to everyone without me as a gatekeeper who isn't sold on the idea yet.
- ...get something out of it, regardless of whether or not I introduce it into the master branch.
- ...have a platform for future tweaks, utility and custom Duality flavors.

Of course this is just an idea, and if it's really just about 1 - 2 methods, it might be a bit too much. If you prefer to submit a PR on this, I'll definitely have a look, but I'm skeptical as to whether I would merge it back.

**Comment by toyners** [comment]
I think putting this into a Duality plugin is a good compromise - I'll look into creating a plugin. 

Thanks for your time and patience on this.
