### ISSUE TITLE
Rectangle shape for rigid collision detection

### ISSUE THREAD

**Issue by brogine** [AdamsLair/duality#276]
I'm currently testing the framework, which i consider very simple and easy to learn as about now.
I'm trying to make a rpg-styled game but i think polygon is not very accurate in this case.

I think Rectangle must be added when editing rigid bodies.
That'd solve a few of my problems.

Thanks Adam for your work.

**Comment by SirePi** [comment]
Well, a Rectangle is in fact a Polygon..

if you check the Rigidbody in the object inspector panel, you will see that you can edit the vertices individually, so it's easier to position them to form a perfect rectangle.

**Comment by ilexp** [comment]
Basically what SirePi said: You can express a rectangle using the existing polygon shape.

Still, it would of course be more convenient if there was an actual "Rect" control, so you would be able to quickly create rectangular polygons. I'm aware that the current RigidBody Editor is not ideal in some cases (see issue #54), but this is currently a rather low-priority task, since all the typical use cases _can_ be accomplished - just sometimes not in the most convenient way.

Other than that, I'm currently working on a Tilemaps plugin, which you can find more about in issue #249 or in the [development report forum thread](http://forum.adamslair.net/viewtopic.php?p=4087#p4087). It won't be released (or officially supported) anytime soon, but in case you're curious, the latest state is available in the `tilemap_wip` branch on GitHub. From a more practical perspective, there are a lot of tilemap-based projects on the [forum](http://forum.adamslair.net/), so I imagine you could get more advice there, if you need help.

**Comment by brogine** [comment]
Yes, but if you have a scene with 50 polygons, you have to draw everyone of them by hand and then edit them individually, there's some time there. 

If you try to check collisions between hand-drawed polygons, you don't get what you are expecting.
I just think this as a minor but useful feature.

**Comment by ilexp** [comment]
> Yes, but if you have a scene with 50 polygons, you have to draw everyone of them by hand and then edit them individually, there's some time there.

Hmm, I think I already answered this, see here:

> Still, it would of course be more convenient if there was an actual "Rect" control, so you would be able to quickly create rectangular polygons. I'm aware that the current RigidBody Editor is not ideal in some cases (see issue #54), but this is currently a rather low-priority task, since all the typical use cases _can_ be accomplished - just sometimes not in the most convenient way.

So yes, you definitely have a point that I acknowledge and it would be more convenient to have a distinct Rect tool, but we already have an issue for this - even though it's currently a low-priority task. :)

For now, you could maybe copy-paste your RigidBodies (Perform a right-click-drag from the source to the target GameObject), use Prefabs, write a custom editor plugin with a script for rect shape generation or write a custom Component that automatically generates a RigidBody for tile-like objects - whichever suits your use case best.
