### ISSUE TITLE
Moving objects with Mouse button won't work properly

### ISSUE THREAD

**Issue by ExAmbitionAl** [AdamsLair/duality#334]
I am making a project, the strategy Stronghold-like game in 2D of course. I written the code to move objects (in this case people) just by clicking the right mouse button. My code is:
`using System;
using System.Collections.Generic;
using System.Linq;
using Duality.Components.Physics;
using Duality.Input;

using Duality;

namespace Codename_Z
{
	public class Player : Component,ICmpUpdatable 
	{
        RigidBody b;
        int x; int y;
        public void OnUpdate()
        {
            
            b = this.GameObj.GetComponent<RigidBody>();
            if (DualityApp.Mouse[MouseButton.Right])
            {
                x = DualityApp.Mouse.X;
                y= DualityApp.Mouse.Y;
                Vector2 v = new Vector2();
                v.X = x;
                v.Y = y;
                b.GameObj.Transform.MoveTo(v);
            }
            
        }
    }
}
`

So, the problem is, When I Click on the map, my object don't respawn on coordinates of my mouse click, but few centimiters down and right. What did I do wrong with code?

Thanks in advance!
Regards!

**Comment by ilexp** [comment]
Hey ExAmbitionAl,

what you're experiencing is a mismatch in coordinate systems. Mouse coordinates are in window space while Transform coordinates are in world space. You will need to transform mouse coordinates into world space first. To do that, you can ask the Camera that is rendering the scene using:

```
Camera mainCam = this.GameObj.ParentScene.FindComponent<Camera>();
Vector3 worldSpacePos = mainCam.GetSpaceCoord(windowPos);
```

Hope this helps you get started! 

If you have further (or followup) questions, please use the forum instead of the GitHub issue tracker. All the getting started / support is happening there while the issue tracking is reserved for bug reports and feature proposals as well as the design work involved in this.
