### ISSUE TITLE
PropertyEditor cuts of decimal number

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#363]
The property editor in dualty only shows three decimal places when you enter a small decimal number.

For example:
0.1  -> displays: 0.1
0.001 -> displays: 0.00 -> :-1: 

Is this a bug?

**Comment by ilexp** [comment]
> Is this a bug?

No, this is intentional. Due to floating point inaccuracy, not limiting the number of decimal places would often result in cases like entering `3` and getting back `2.999948231` or similar. By default, floating point numbers are rounded to two decimal places, but each property can adjust this number as needed using the `[EditorHintDecimalPlaces]` attribute.
