### ISSUE TITLE
Create and Publish a 'New Project' Template for Editor and Core Plugins

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#372]
It would be nice if you can create a new editor plugin just by selecting the corresponding project template.

The editor should create a visual studio solution (template) with all required dependencies.

**Comment by ChristianGreiner** [comment]
Maybe a data driven template system would be ideal, so you can create new project templates without modifying the sourcecode.

I think a simple XML file  is most suitable for this.

What do you think guys?

**Comment by ilexp** [comment]
What Duality already does is create an editor plugin for your specific project, similar to the core plugin - it's just not part of the solution file by default. In order to create additional Duality editor and core plugin projects, a project template would indeed be nice.

I'm pretty sure Visual Studio already has a sophisticated project template system, so this should probably not be done in Duality, but as a set of Visual Studio templates that can be installed as needed.

Anyone with experience on this?

**Comment by ChristianGreiner** [comment]
I found an useful link for creating templates in visual studio:

https://www.jayway.com/2015/03/13/visual-studio-how-to-create-a-solution-template-with-multiple-projects/

**Comment by Barsonax** [comment]
Iam looking into this atm.

**Comment by Barsonax** [comment]
Made a start by creating a VSIX project and templates for plugins and editor plugins. Not really sure where to put this so for now just a zip:
[DualityTemplate.zip](https://github.com/AdamsLair/duality/files/1392206/DualityTemplate.zip)

It currently uses nuget to get the duality dll's. Not really sure if this is prefered but this is not that hard to change.

**Comment by Barsonax** [comment]
It would be nice if you create a duality solution that it actually contains duality itself aswell. Will try and see if this is possible.

**Comment by Barsonax** [comment]
Currently researching if its possible to:
-Create a solution template that creates everything you need to start making a game with duality. Pretty much what you would get if you downloaded duality and started it once.
-Create a plugin project template **Done**
-Create a editor plugin project template **Done**
-Create a duality component item template

**Comment by Barsonax** [comment]
Wizard doesn't seem to be working and neither can I debug it because it just doesn't want to load the symbols. Not sure why.

Anyways here's the zip
[DualityTemplate.zip](https://github.com/AdamsLair/duality/files/1393775/DualityTemplate.zip)

**Comment by ilexp** [comment]
Very nice progress documentation 👍 

> Made a start by creating a VSIX project and templates for plugins and editor plugins. Not really sure where to put this so for now just a zip:
[DualityTemplate.zip](https://github.com/AdamsLair/duality/files/1392206/DualityTemplate.zip)

There's the Visual Studio marketplace, but uploading it would mean we'd have a hard maintenance requirement - maybe create a Wiki page for now with a link to the zip and a short explanation how to use it?

@ChristianGreiner Would the above be what you imagined when you created the issue?

**Comment by Barsonax** [comment]
Iam still working on it though that zip I linked is not finished or ready to be used. I does work now meaning that it doesn't crash during the creation of the solution. Seems Any cpu is evil and you have to set it to x86.

Iam not using the zip based export method any more. I now have a VSIX project, 2 projects for the plugin and editor plugin and a project for the 'duality solution'. Still gotta write the wizard to make the last one work properly (as in create folder structure and add everything duality needs to run) and have to customize the plugin and editor projects so that they have the correct settings.

**Comment by Barsonax** [comment]
So what I will do for now is make a vsix package with a plugin and editor plugin template and a template for a component. A vsix is easy to install or deinstall and you if we ever want to publish a duality extension we could do that too but not for now.

The project templates will assume that the default folder structure is used.

However there is some duality logic that uses hardcoded paths to the project files and this code will break if you have a project with a different name. Not sure if this is a serious problem though as I renamed the project files in pathfindax without having any problems.

**Comment by Barsonax** [comment]
@ChristianGreiner, @ilexp made a new GitHub repo for the templates:
https://github.com/Barsonax/DualityExtension

And here is the extension ready to be installed: 
[DualityExtension.zip](https://github.com/AdamsLair/duality/files/1407521/DualityExtension.zip)

**Comment by ilexp** [comment]
> @ChristianGreiner, @ilexp made a new GitHub repo for the templates:
> https://github.com/Barsonax/DualityVSExtension

Sounds good. Thanks!

So.. should we close this issue now? @ChristianGreiner

**Comment by ChristianGreiner** [comment]
I tested the VS Extension and I'm totally happy with it! Nice work @Barsonax !
@ilexp We can close this issue now :)

**Comment by ilexp** [comment]
Great, closing this. Thanks everyone 👍
