### ISSUE TITLE
Engine throws a deserialization exception when attempting to load a Prefab that uses a non-existent Component class

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#389]
I have a prefab that holds a component that doesn't exist anymore.
So the editor throws an error, that the component wasn't found.
Thats understandable, but the engine  throws also this exception:

`````
[Core] Error:           Error reading object: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Log.Type(TypeInfo type) in c:\projects\duality\Duality\Utility\Log\Log.cs:line 319
   at Duality.Serialization.XmlSerializer.ReadMemberInfo(XElement element, ObjectHeader header) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 675
   at Duality.Serialization.XmlSerializer.ReadObjectBody(XElement element, ObjectHeader header) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 464
   at Duality.Serialization.XmlSerializer.ReadObjectData(XElement element) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 444
[Core] Warning:         Missing or Disposed Component in GameObject 'GameObject "Prophet"'. This should never happen and is likely the cause of malformed data
````

**Comment by ilexp** [comment]
By "doesn't exist anymore" you mean that the Component class does not exist anymore, correct?

**Comment by ChristianGreiner** [comment]
Yes, that's correct.

**Comment by ilexp** [comment]
### Progress

- Added a unit tests that reproduces this behavior.
- Fixed the error by improving Log.Xy formatting methods with regard to null parameters.

### Immediate ToDo

- Investigate Serializer implementations for error-prone behavior.
  - `ObjectHeader` should still be able to provide the original `TypeString` even when the resolve step failed, so `BinarySerializer` and similar implementations can still use it for type layout lookups.
  - Not being able to resolve a type should cause an immediate error log rather than relying on subsequent exceptions.
  - Follow up exceptions after failing to resolve a type should be avoided. Ideally, all of them.
  - etc.
- Fix error-prone behavior that was discovered.
- Release a fixed binary package.

------

@ChristianGreiner The bug has been fixed, but it will take me some more time until I get to do a binary release, since I want to address the above points first. You can build Duality from the repository master branch to get the fix early. Replacing `Duality.dll` (as well as .xml and .pdb) in your project with the custom built one should do the trick.

**Comment by ilexp** [comment]
### Progress

- BinarySerializer and XmlSerializer implementations act now a little more robust when dealing with deserializing an object of a non-existent type. They should, in most cases, be able to continue loading type layouts and deserialize child objects while omitting the steps that cannot be performed.
- Binary release is in progress. Check for package updates in about 15 minutes.
