### ISSUE TITLE
Interfaces will not removed from lists in the property editor

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#425]
See this issue: https://github.com/AdamsLair/duality/issues/420

When you added a interface to a list and try to remove it, it's going to be null.
As soon as you start the sandbox, the interface appears again...

![](https://thumbs.gfycat.com/EssentialIndolentBlueshark-size_restricted.gif)
https://thumbs.gfycat.com/EssentialIndolentBlueshark-size_restricted.gif

**Comment by ilexp** [comment]
This looks like it could easily be an issue with game code. Can you provide a minimal code sample that reproduces this in a fresh Duality install?

**Comment by ilexp** [comment]
Came up with a minimal example myself after a quick test:

```
	public interface IBar { }
	public class Bar : IBar
	{
		public string Text { get; set; }
	}
	public class Foo : Component
	{
		public List<IBar> Bars { get; set; }
	}
```

In fact, this could very well be related to issue #420, since clicking the X mark _twice_ will truly null the list item, while clicking only once will result in the value "coming" back.

This might be a UI issue that could be originating from the AdamsLair.WinForms dependency.

**Comment by ilexp** [comment]
After some more testing it turns out that the main reason for the unwanted revert is that the containing Scene does not get flagged as modified / unsaved by creating or deleting a list item instance. (It does when editing that instance, so changing any other value will be a suitable workaround until this is fixed.)

It has yet to be investigated why exactly no change event is fired in this case.

**Comment by ilexp** [comment]
In the normal case, deeply nested property editing is transformed into editor PropertyChanged events in the `ComponentPropertyEditor.OnValueChanged` implementation (as well as the `ResourcePropertyEditor` equivalent). The problem in the failure case we observe here is that setting a list (or dictionary?) element does not invoke the `OnValueChanged` method chain. This is likely an issue within the `AdamsLair.WinForms` dependency.

Investigate and fix.

**Comment by ilexp** [comment]
Can confirm that OnValueChanged events are skipped in `AdamsLair.WinForms` for cases where the reflected item type does not match the container item type in list and dictionary editors. 

Did not investigate the root cause yet, but I'd guess it has something to do with the fact that setting null changes the reflected type of the item, so the editor that is responsible for propagating the event gets disposed.

**Comment by ilexp** [comment]
### Progress

- Fixed issue #420 
- Investigated potential causes for the "revert" when entering Sandbox mode, found the above.

### Immediate ToDo

- Investigate potentially lost `OnValueChanged` message due to removing the modified property editor and replacing it with a new one.
- Take a look at `MemberwisePropertyEditor` to fix the same issues as with list and dictionary editors:
  - Editor re-creation in the reflected type verification step needs to run `PerformGetValue` on the newly created editor.
  - Potentially lost `OnValueChanged` message due to old editor removal and new editor creation (see above)

**Comment by ilexp** [comment]
### Progress

- Investigated `MemberwisePropertyEditor` to look for the same kind of uninitialized editor bug that was present in list and dictionary editors after replacing a reflected type editor with a different one. As it turns out, `MemberwisePropertyEditor` already calls `PerformGetValue`, so no bug here. It may still be prone to the `OnValueChanged` bug.

### Immediate ToDo

- Investigate potentially lost `OnValueChanged` message due to removing the modified property editor and replacing it with a new one, in memberwise, list and dictionary editors..

**Comment by ilexp** [comment]
Fixed and release in progress. Package updates should be available in about 30 minutes.
