### ISSUE TITLE
Object Inspector Undo / Redo Support for Adding / Removing Elements to IList and IDictionary

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#426]
### Summary

While the Object Inspector allows you to Undo / Redo modifying list and dictionary elements properly, there is currently no implementation for Undo / Redo support on adding and removing elements.
### Analysis
- There is no Add / Remove element event handler in list and dictionary property editors. This would be a required change in `AdamsLair.WinForms`.
- There is no Undo / Redo action that represents this kind of operation in a generic way yet.

**Comment by deanljohnson** [comment]
I'm thinking about looking into this. When I first started contributing to Duality, you weren't accepting PR's for `AdamsLair.WinForms`. Is that still the case?

**Comment by ilexp** [comment]
Nope, all the Duality-related projects are open for PRs now. If you want to tackle this, go ahead!

**Comment by deanljohnson** [comment]
Awesome. Here are some notes on my progress and what I have learned:

I was first going to take an event based approach where the IList and IDictionary PropertyEditors send events whenever an item is added to a list they control. This works fine on the `AdamsLair.WinForms` side of things, but I had trouble figuring out the right way to hook into these events from Duality.

As far as I can tell, the DualityPropertyGrid does not have a point I could hook into for when a property editor is removed. So while I could subscribe to the added and removed events on the IList and IDictionary editors, I couldn't unsubscribe. Furthermore, creating an UndoRedoAction in this design is a problem. Other UndoRedoActions contain the code that does and undoes their associated actions. With the event design I was planning, the action is already done within the PropertyEditors.

Now I'm thinking about taking a similar approach to the [IList index setters](https://github.com/AdamsLair/winforms/blob/c59be26c15ced5ed713e43f3b4db9d4360ca8e51/WinForms/PropertyEditing/PropertyEditors/IListPropertyEditor.cs#L30) and [IDictionary key value setters](https://github.com/AdamsLair/winforms/blob/c59be26c15ced5ed713e43f3b4db9d4360ca8e51/WinForms/PropertyEditing/PropertyEditors/IDictionaryPropertyEditor.cs#L25) where they use a delegate to perform the operation on the collections they control. I'd write a default that adds and removes items as the editors do now, but allow the delegate to be switched to something on the Duality side.

With the above redesign, I could hook into the editors like currently done [here](https://github.com/AdamsLair/duality/blob/eac3700343e3a203b1f62906aed8fc8228ddc6df/Source/Editor/DualityEditor/Controls/DualitorPropertyGrid.cs#L71-L80). Then I'd write the UndoRedoAction for each and that should be most of what has to be done!

**Comment by deanljohnson** [comment]
Going forward with the delegate approach. Events would require an awkward UndoRedoAction to be implemented because the items would have already been added or removed when the UndoRedoAction was first added the the Undo/Redo stack. That could be solved if there was a way to push an action onto the UndoRedo stack without automatically `Do()`ing it but I'm not sure if we want to add to that API for this feature - the current API encourages a cleaner design overall. 

I'm not liking the delegate definition right now:
```
public delegate bool ElementAdder(IList<object> targetObjects, int count, Type elementType, Type reflectedArrayType);
public delegate bool ElementRemover(IList<object> targetObjects, int count, Type reflectedArrayType);
```
The ugliness mostly comes from having to deal with arrays. Since they can't be resized without creating a new instance, these need to return a boolean specifying whether or not writeback should be done. That is also why they are passed `IList<object>` rather than an `IEnumerable<object>`. The `reflectedArrayType` parameter is also only there to support arrays. It's not terrible, but I feel like this is a fair bit of work for delegate implementers. On the Duality side I can use the PropertyEditor instance to get the object being edited. That should will allow me to implement the undo/redo the actions.

About the `elementType` parameter - I'm not entirely clear about why it is used in the existing code. It is used [here](https://github.com/AdamsLair/winforms/blob/c59be26c15ced5ed713e43f3b4db9d4360ca8e51/WinForms/PropertyEditing/PropertyEditors/IListPropertyEditor.cs#L271). Is there a reason that couldn't be replaced with `reflectedArrayType`?

**Comment by ilexp** [comment]
> Now I'm thinking about taking a similar approach to the IList index setters and IDictionary key value setters where they use a delegate to perform the operation on the collections they control. I'd write a default that adds and removes items as the editors do now, but allow the delegate to be switched to something on the Duality side.

Sounds good! I think this approach is the least invasive one to pull off, and also matches with the current design on how this is done for other PropertyEditors 👍 

> About the elementType parameter - I'm not entirely clear about why it is used in the existing code. It is used here. Is there a reason that couldn't be replaced with reflectedArrayType?

It's been a while since I was around that code, but as far as I recall there can be cases where you do not have a reflected array type - like when editing an array where the array instance itself is actually null. Whether or not the reflected type itself will be null in those cases, or whether these cases can lead to linked code being executed in the first place I'm not sure. 

Feel free to look into this, I think it's entirely possible you can replace it with `reflectedArrayType`, but be careful that in the case you're dealing with you can guarantee that it is defined. Fall back to the declared `elementType` otherwise.

> The ugliness mostly comes from having to deal with arrays. Since they can't be resized without creating a new instance, these need to return a boolean specifying whether or not writeback should be done.

Ah.. that's a good point. How about something like this?

```csharp
public delegate bool ElementInserter(IEnumerable<IList> targetLists, int index, IEnumerable<object> items);
public delegate bool ElementRemover(IEnumerable<IList> targetLists, int index, int count);
```

- `targetLists` provides the multi- or single selection of list values to be modified.
- `index` describes the index at which the new elements should be inserted. Can be "one-past-the-end" for a regular add.
- `items` are one or more values to be inserted. If they can be assigned to the list elements, that's good, if their type cannot, then it will throw an exception at runtime.
- `count` describes how many elements should be removed, starting from index.

Both inserter and remover are lacking any specific list type, mostly because this information can be derived entirely from each individual `IList` element. If it supports adding or removing, nothing to do here. If it's an array, you can just create a new array of the same type as the old one on a per-element basis. 

This will also make cases work where you have one `object[]` and one `string[]` in multi-selection, which is reflected to `string[]` for editing, and then add a new string somewhere. While you can add it to both arrays without problems, the array type you need to create is different for each element of the multi-selection.

**Comment by deanljohnson** [comment]
Wouldn’t there need to be an index for each list? If the lists have different sizes, there is no sensible value to indicate where to add/remove the item unless we went with a magic value like -1. The ilist editor only ever adds/removes at the end of the lists, so I was going to use that assumption and not pass any kind of index. That means insertion isn’t possible, but it doesn’t seem like the IListPropertyEditor supports insertion anyways.

**Comment by ilexp** [comment]
> The ilist editor only ever adds/removes at the end of the lists, so I was going to use that assumption and not pass any kind of index. That means insertion isn’t possible, but it doesn’t seem like the IListPropertyEditor supports insertion anyways.

Yep, there's no support for insertion yet - but that's just a UI thing which could be fixed / extended at some point. Providing an index in the API ensures that we don't block this path.

> Wouldn’t there need to be an index for each list? If the lists have different sizes, there is no sensible value to indicate where to add/remove the item unless we went with a magic value like -1.

If the lists have different sizes, adding an element would currently either truncate the lists to their smallest, or extend the smaller lists to match the largest. Not sure how exactly that's implemented, but in any case the insertion index would be constant across targets.

From the API perspective you're right, but I'm not sure there is a case where you would use a list property editor to simultaneously insert or remove with different indices for different elements of a multi-selection. Even if we had a "add new item to each lists end" button there, there would be no way to then edit or even see that value with multi-selection active.

**Comment by ilexp** [comment]
> If the lists have different sizes, adding an element would currently either truncate the lists to their smallest, or extend the smaller lists to match the largest. Not sure how exactly that's implemented, but in any case the insertion index would be constant across targets.

Ah, wait a second. If the lists have different sizes, normalizing them into one size already requires doing something different to each target list. We can see that in the [code snippet you linked](https://github.com/AdamsLair/winforms/blob/c59be26c15ced5ed713e43f3b4db9d4360ca8e51/WinForms/PropertyEditing/PropertyEditors/IListPropertyEditor.cs#L271) where each list is adjusted individually.

We can't really reflect that in a multi-element insert / remove API without more or less providing a list for every single parameter, which would be really ugly. One way to get past that would be this:

```csharp
public delegate bool ListResizer(IEnumerable<IList> targetLists, int size);
```

So we'd have a resize delegate that could make sure all lists have a certain size, which could also reflect 100% of the current list editors add / remove functionality. Other add / remove / insert cases could be expressed as a combination of resize and setvalue calls.

One issue would be Undo / Redo support that shouldn't end up with 10 items when removing element zero of a 10 item list, but we might dodge that bullet [because macro-support might already merge them](https://github.com/AdamsLair/duality/blob/e572fba8ed14acc8c95dd2a74e409e8605fb0a97/Source/Editor/DualityEditor/Controls/DualitorPropertyGrid.cs#L107-L116) into a single UndoRedo action.

**Comment by deanljohnson** [comment]
> We can't really reflect that in a multi-element insert / remove API without more or less providing a list for every single parameter, which would be really ugly. One way to get past that would be this:

>public delegate bool ListResizer(IEnumerable\<list\> targetLists, int size);

I like the idea of the ListResizer delegate. Add and removing are so similar that it was kind of awkward to have separate delegates, but the ListResizer removes that difference from the API. This also means only a single UndoRedoAction needs to be implemented.

I don't think `IEnumerable<IList> targetLists` will work in the API though because of the Array writeback issue - a delegate implementation couldn't overwrite the array element in the targetLists enumerable. If the delegate was instead this:
`public delegate bool ListResizer(IList<IList> targetLists, int size);`
Then they could simply overwrite the index of `targetLists` with the new array and the IListPropertyEditor can perform the writeback.

Regarding not having to send a type parameter: I was trying to keep the type determination in the IListPropertyEditor since it already has all the functionality necessary and any implementation of the delegate would have to do the same operations anyways. It does clutter the API, but is there a case where different delegate implementations would calculate the types differently? If not, is the slightly messier API worth simplifying the delegate implementation?

**Comment by ilexp** [comment]
> Regarding not having to send a type parameter: I was trying to keep the type determination in the IListPropertyEditor since it already has all the functionality necessary and any implementation of the delegate would have to do the same operations anyways. It does clutter the API, but is there a case where different delegate implementations would calculate the types differently? If not, is the slightly messier API worth simplifying the delegate implementation?

Good point! Let's add the type back then, but maybe just a single "element type" parameter without distinguishing between reflected and declared. I think the decision which one to use can be made by the caller, before invoking the delegate. It can be used to both initialize new elements and determine the array type to be instantiated.

> I don't think IEnumerable<IList> targetLists will work in the API though because of the Array writeback issue - a delegate implementation couldn't overwrite the array element in the targetLists enumerable. If the delegate was instead this:
public delegate bool ListResizer(IList<IList> targetLists, int size);
Then they could simply overwrite the index of targetLists with the new array and the IListPropertyEditor can perform the writeback.

Sounds good 👍

**Comment by deanljohnson** [comment]
Alright, so I'm working on the Duality side of this and am having issues with array writeback. In order to perform the writeback, I need the object being edited (that has the list property). I cannot find a good way to get the edited object. I have [this](https://github.com/deanljohnson/duality/blob/4ac6d34646fa36c470545e5f8e8bae71abc0c864/Source/Editor/DualityEditor/UndoRedoActions/ResizeListAction.cs#L72) which works fine when editing a single object, but I'm not sure if relying on the DisplayedValue property of the parent editor is safe. When editing multiple objects, this fails as DisplayedValue is equal to only one of the multiple objects selected.

Is there a good way to get the object/s being edited from the IListPropertyEditor? The only other idea I have right now is walking down to the IList property from the PropertyGrid that the PropertyEditor belongs to but that is going to be messy.

**Comment by ilexp** [comment]
> I have this which works fine when editing a single object, but I'm not sure if relying on the DisplayedValue property of the parent editor is safe.

Yep, that this is not a safe way to do it. We'll need something else.

> Alright, so I'm working on the Duality side of this and am having issues with array writeback. In order to perform the writeback, I need the object being edited (that has the list property). I cannot find a good way to get the edited object

I don't have a solution right now, but maybe take a look at the [EditPropertyAction](https://github.com/deanljohnson/duality/blob/4ac6d34646fa36c470545e5f8e8bae71abc0c864/Source/Editor/DualityEditor/UndoRedoActions/EditPropertyAction.cs) for inspiration. It's the action that is used for redirecting regular property get / set operations, and it doesn't actually refer to the PropertyEditor at all and operates directly on the property itself. Maybe a similar approach would make sense here?

**Comment by deanljohnson** [comment]
> I don't have a solution right now, but maybe take a look at the EditPropertyAction for inspiration. It's the action that is used for redirecting regular property get / set operations, and it doesn't actually refer to the PropertyEditor at all and operates directly on the property itself. Maybe a similar approach would make sense here?

Unless I'm misunderstanding, that same method won't work here - that action already has a reference to the objects with the property that is being edited. In my case, all I can get access to is the PropertyInfo. EditPropertyAction receives those references to the objects via protected methods on PropertyEditor. They are then passed to the following delegate: `public delegate void PropertyValueSetter(PropertyInfo property, IEnumerable<object> targetObjects, IEnumerable<object> values);` which is notably different than the delegates in place on the IList and IDict editors in that the current delegates pass the target list and dictionaries rather than the target objects that contains the list/dict properties. The current delegate could be changed to `void ListResizer(PropertyInfo prop, IEnumerable<object> targetObjects, int size, Type elementType)`....

**Comment by ilexp** [comment]
Hmm, you're right. I think we need to adjust the delegates to support the writeback case. Should be adjust both `ListResizer` and the ones for element add / remove? We don't currently support that, but there _are_ immutable dictionaries too, so we should be prepared for the writeback case for both lists and dictionaries.

**Comment by deanljohnson** [comment]
> Hmm, you're right. I think we need to adjust the delegates to support the writeback case. Should be adjust both ListResizer and the ones for element add / remove? We don't currently support that, but there are immutable dictionaries too, so we should be prepared for the writeback case for both lists and dictionaries.

I think yes, even if just to achieve a consistent API design.

I've been investigating going this new route - giving IListPropertyEditor a delegate like: `void IListResizer(PropertyInfo listProp, IEnumerable<object> targetObjects, int size, Type elementType)` where `targetObjects` are the objects that have the IList property we want to resize. That poses it's own issues I haven't been able to fix - the target objects are managed by the parent editor and the parent editors value is inaccessible from the child editor (the IListPropertyEditor in this case). EditPropertyAction manages this through MemberwisePropertyEditor which sets the Setter property of child editors [here](https://github.com/AdamsLair/winforms/blob/7560c8e449232d929cf65cb4297b05f7ee342678/WinForms/PropertyEditing/MemberwisePropertyEditor.cs#L143). Child editors never get access the target objects and they can use their regular setter to do their work. I can't simply call the parent editors Getter because that property is set only. It's the same with the IListPropertyEditor's setter delegate - it is set only and so cannot be called from the UndoRedoAction.

What do you think of adding a public `SetValues(IEnumerable<IList> lists)` method to IListPropertyEditor? The UndoRedoAction implemented on the duality side could just use that method as needed. The current resizing delegate would remain and be the initial point from which the UndoRedoAction is created. Subsequent undo/redo's of the action would use the `SetValues(IEnumerable<IList> lists)` method.

**Comment by ilexp** [comment]
Okay, so starting from the earlier approach:

> If the delegate was instead this:
>```csharp
>public delegate bool ListResizer(IList<IList> targetLists, int size);
>```
> Then they could simply overwrite the index of targetLists with the new array and the IListPropertyEditor can perform the writeback.

The problem is that, for an UndoRedoAction to work, the implementation behind the delegate needs to be able to autonomously perform a writeback, rather than relying on the parent PropertyEditor, because that PropertyEditor might not even exist anymore (or in the wrong state) when the UndoRedoAction is applied or un-applied. Selecting a different object or closing the Object Inspector will do that - but we can still undo back, or redo forth.

If this is correct, then adding public setter methods to the IListPropertyEditor will not solve our problem. We can't depend on the PropertyEditor, and even the [PropertyGrid dependency in EditPropertyAction](https://github.com/deanljohnson/duality/blob/4ac6d34646fa36c470545e5f8e8bae71abc0c864/Source/Editor/DualityEditor/UndoRedoActions/EditPropertyAction.cs) is only to make sure it invalidates to display the new value - it's entirely optional.

This means we need to pass everything we need as delegate parameters in some persistent way. The setter delegate in MemberwisePropertyEditor does this by passing both reflection member and target objects, but it also has an easier use case, because in the context of this specific editor, we _know_ that the we will always operate on either a property or a field. In case of every other PropertyEditor, we do not know that - it could be anything. One example is the [BatchInfoPropertyEditor](https://github.com/deanljohnson/duality/blob/4ac6d34646fa36c470545e5f8e8bae71abc0c864/Source/Plugins/EditorBase/PropertyEditors/BatchInfoPropertyEditor.cs) where every setter is internally mapping the values to material properties, but any custom PropertyEditor can spawn a child editor that happens to be an IListEditor, and supply whatever getter and setter it wants.

So at this point we're really in a bad place where we can only hope that the getter and setter transcend the lifetime and state of their PropertyEditor, but even in the case of the BatchInfoPropertyEditor, [we can already see that this is not true](https://github.com/deanljohnson/duality/blob/4ac6d34646fa36c470545e5f8e8bae71abc0c864/Source/Plugins/EditorBase/PropertyEditors/BatchInfoPropertyEditor.cs#L425). We could only make assumptions here and hope for the best, but I don't think this is a route that we want to go down. 

Instead of trying to fix this design flaw of `PropertyEditor` from a really unfortunate angle, let's try a compromise and drop writeback support in UndoRedo for list resize and dictionary add / remove operations. We should be able to use the existing design:

```csharp
public delegate bool ListResizer(IList<IList> targetLists, int size);
```

and [let the list editor perform the writeback](https://github.com/AdamsLair/winforms/blob/7560c8e449232d929cf65cb4297b05f7ee342678/WinForms/PropertyEditing/PropertyEditors/IListPropertyEditor.cs#L279) where needed. The [DualitorPropertyGrid could](https://github.com/deanljohnson/duality/blob/4ac6d34646fa36c470545e5f8e8bae71abc0c864/Source/Editor/DualityEditor/Controls/DualitorPropertyGrid.cs#L195) do a quick reflection check for readonly lists and return true in that case, but the UndoRedoAction will be unable to trigger a late writeback when going through the history. It will not make undo / redo work for array resizing, but given that most lists are probably not readonly, we still gain a new feature most of the time. Same applied for dictionary element add / remove.

What do you think?

**Comment by ilexp** [comment]
> The DualitorPropertyGrid could do a quick reflection check for readonly lists and return true in that case, but the UndoRedoAction will be unable to trigger a late writeback when going through the history. It will not make undo / redo work for array resizing [..]

Actually, now that I think about it, we might get lucky here. If we return true from the IListPropertyEditor resizer delegate, that PropertyEditor will do the writeback - which _could_ in fact already be rerouted [into the property or field setter](https://github.com/deanljohnson/duality/blob/4ac6d34646fa36c470545e5f8e8bae71abc0c864/Source/Editor/DualityEditor/Controls/DualitorPropertyGrid.cs#L179-L186), triggering the writeback itself as a separate UndoRedo action. And luckily, the DualitorPropertyGrid [also wraps them into a single macro action](https://github.com/deanljohnson/duality/blob/4ac6d34646fa36c470545e5f8e8bae71abc0c864/Source/Editor/DualityEditor/Controls/DualitorPropertyGrid.cs#L109-L118)... so if this turns out to be true, the problem might solve itself, with just the above approach.

If it doesn't, I would still be fine with the compromise, if it does, then all the better.

**Comment by deanljohnson** [comment]
I think this is a good option. We get a new feature without disrupting the API too much - I think any better way of fixing this will require more significant changes that don't seem to be worth the trouble at this point. I'll go forward with your idea: no writeback support unless it comes essentially automatically from the macro action. Sounds good.

**Comment by ilexp** [comment]
Done by @deanljohnson
