### ISSUE TITLE
Introduce a way to load the last open scene in the editor

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#445]
At the moment the editor doesn't open any scene after you launched it. 
It would be nice, if you could toggle an option, so the editor loads the last open scene automatically .

The toggleable option have to be stored in the AppData (default UserData).
(see [here](https://github.com/AdamsLair/duality/issues/13#issuecomment-137739542))

Some thoughts from the community:
> [22:20] SirePi: maybe a question, after you open "do you want to load the last edited scene?"
> [22:21] loeller: I think a popup is rather annoying
> [22:22] loeller: but most of the times you want to continue with the one you worked previously
> [22:23] loeller: actually, it can be a toggleable setting. But the popup at the start is not elegant imo

What do u think?

**Comment by mfep** [comment]
'with the one you worked **on** previously'

**Comment by ilexp** [comment]
Sounds good to me!

> The toggleable option have to be stored in the AppData (default UserData).
(see here)

AppData and UserData are for the game only, not the editor. This option would be part of the editor user settings, as serialized in `EditorUserData.xml`.

Since editor user data is not editable at a central place (as still planned in issue #13), we'd need to find a temporary place to put this option, or just default to true and require users who don't want this behavior to edit the `.xml` file by hand. The later option would be a good candidate for a first iteration.

**Comment by Barsonax** [comment]
Made a PR that adds this functionality, still WIP.

**Comment by ilexp** [comment]
Done by @Barsonax
