### ISSUE TITLE
"Cannot access a disposed object", Object name : 'LogEntryList'

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#451]
### Summary

After entering SandBox mode, the log view spams continuously this error : http://pastebin.com/ZfiFy9L3

### How to reproduce

I think it happened after Duality crashed because of a newly added buggy component, which was removed after restarting Duality. I haven't been able to reproduce it.

### Workaround

Restarting Duality removed the problem.

**Comment by ilexp** [comment]
It _looks_ like an editor-internal error, but I'm not sure how this specific one could happen. If you manage to reproduce this later, please add more details in a comment. Otherwise, I'll likely have to do a blind fix, i.e. we won't know for sure whether it's actually gone or just hasn't happened again yet.

**Comment by ilexp** [comment]
Managed to reproduce and fix it. When closing a LogView and opening a new one, the old LogView was still subscribed to log events.

Release in progress. Closing this.
