### ISSUE TITLE
Tileset Editor and Tile Palette don't render with the good filter

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#452]
### Summary

Tileset Editor and Tile Palette seem to always render using the linear filter, instead of the texture's filter.

**Comment by ilexp** [comment]
Tileset Editor and Tile Palette are using their own filter that is chosen using a heuristic based on displayed tile size and actual tile size. First, a base size is chosen that is within a certain range - if the actual tile size is a rounded multiple of that base size, no filtering is used. Otherwise, linear filtering is active.

So, the displayed size of the tile in the Tile Palette / Tileset Editor is not necessarily the one the tiles are intended to be displayed in, as it favors providing a good overview over being pixel-accurate. Imagine 200x200 tiles or 4x4 tiles - you wouldn't really want them to be displayed 1:1. Since the sizes do not match, the texture filtering is likely not chosen to be ideal for the Tile Palette displayed size.

Closing this for now. (But feel free to comment if you're not convinced or have a better solution than the currently implemented one!)
