### ISSUE TITLE
Usage of multiple tilesets in a single tilemap

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#457]
At the moment there is no way to assign multiple tilesets to a single tilemap. If you want to use e.g. two different tilesets, you have to create a new gameobject with a new TileMap- and TileMapRenderer-Component. Then you have to select the new added gameobject to paint the tiles of the other tileset.
In my opinion this isn't a really good workaround.

So there should be a way to add other tilesets to an list of tilesets in the tilemap.
The tile palette in the editor should recognize which tileset did you selected in the tilemap.

In [Tiled](http://www.mapeditor.org/) you can add multiple tileset to the current document and paint tiles in any tilemap layer.
TIled sets an unique id for each tile in every tileset.
The first tile in the first tileset has the id 1. The last tile e.g. 72.
In the second tileset the id of the first tile doesn't begin with 1, but rather with 73.
With this approach you can discern each tile.

What do u think?

**Comment by ilexp** [comment]
A `Tileset` is designed as a collection of tiles that are to be used in a single `Tilemap`, so it doesn't really make sense to have multiple tilesets per tilemap: If you need tiles from multiple tilesets in the same layer, then you just found out that they should in fact be one tileset, or that one of your tilesets should be extended by a select few tiles from the other.

This is not something that simply isn't implemented, it would actually break the design of the `Tileset`, which is optimized for efficiency and performance. You, as a user, have to make a conscious choice about the contents of each tileset in order to allow that.

Using multiple layers with different tilesets can also be a solution. The Tilemap creation dialog can help you set up any number of layers quickly, so it shouldn't be too much of an issue usability-wise.
