### ISSUE TITLE
Introduce Serialization and Cloning Surrogates for HashSet<T>

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#472]
### Summary

There already are serialization and cloning surrogates for `Dictionary<T,U>`, but there is none for `HashSet<T>` yet. While serialization and cloning still work, they're rather inefficient on `HashSet<T>` because of examining its internal structure as opposed to just dealing with the collection items. Introducing optimized surrogates for `HashSet<T>` would greatly improve this.

### Analysis

- The surrogate for `Dictionary<T,U>` can likely serve as a basis for the new `HashSet<T>` surrogates, though they will be a little more reflection-dependent because of the lack of a non-generic `ISet` interface.
- Introducing a new surrogate _should_ be backwards compatible, but double-check this.

**Comment by Barsonax** [comment]
Opted to use the dynamic keyword since there is no non generic ISet interface. See PR #609.

**Comment by Barsonax** [comment]
Came across a limitation of dynamic. If you put in a private type (like private class SomeClass {}) in the hashset the code will throw runtimebinding exceptions when calling a method like clear on the hashset. Its kinda weird but it seems like it threats the entire hashset as private a private type instead of just the contents. While this is a uncommon scenario it might happen. Still does it even make sense to serialize private types?

**Comment by ilexp** [comment]
Continued this thread in PR #609, see [here](https://github.com/AdamsLair/duality/pull/609#issuecomment-358010097).

**Comment by ilexp** [comment]
Done by @Barsonax.
