### ISSUE TITLE
Tilemaps errors when changing collisionsources

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#494]
### Summary
Iam getting some errors after setting a collision source to null in the tilemap collider. After doing this and saving you get a index out of range exception and from that point on you can no longer save that scene.

This might also cause other bad stuff to happen since I have a scene where the old collision shapes wont go away but I was not able to reproduce this afterwards.

EDIT: after manually deleting the shapes they did not come back so this is a workaround for that bug.

### How to reproduce

Steps:
-Create a new tilemap with collision,
-Set one of the collision sources in the tilemap collider to null
-Hit save

Result:
Bugged scene that cannot be saved anymore

### Attachments

![image](https://cloud.githubusercontent.com/assets/19387223/22618666/d6d94cb6-eae2-11e6-9eae-c36d4cd66ceb.png)

**Comment by ilexp** [comment]
Thanks for reporting! 

This is likely a series of second-hand bugs caused by a single exception that left the `TilemapCollider` in an invalid state. The goal in fixing this would be to identify what caused the very first exception and fix that. 

I'm putting this up for grabs in case anyone wants to give this a try (please comment if you do).

**Comment by ilexp** [comment]
Started investigating this, but I can't reproduce the bug using the steps you provided. Can you reproduce this using a fresh install of Duality?

**Comment by ilexp** [comment]
Got it. The crucial part was that _all_ sources had to be null. Fixed and binary release in progress.
