### ISSUE TITLE
Switching between Scene Editor and Game View changes mouse's wheel speed value

### ISSUE THREAD

**Issue by ChatPion** [AdamsLair/duality#498]
### Summary

Basically what is said in the title.

In the following gif, I logged the value of DualityApp.Mouse.WheelSpeed if it wasn't null.
![mouse_wheel_bug](https://cloud.githubusercontent.com/assets/3697923/22857118/2db72e2e-f09f-11e6-99e0-69bf1029a91f.gif)

**Comment by ilexp** [comment]
The Scene View does not forward any input to the game, only the Game View does. What you're seeing is likely the effect of the mouse becoming unavailable to your game, rather than a switch between views - something like the mouse wheel value jumping to zero from its previous value, producing a false wheel speed.

Can you extend you log output to the following and share your results?

1. `DualityApp.Mouse.Wheel`
2. `DualityApp.Mouse.WheelSpeed`
3. `DualityApp.Mouse.Y`
4. `DualityApp.Mouse.YSpeed`
5. `DualityApp.Mouse.IsAvailable`

**Comment by ChatPion** [comment]
![dualityeditor_2017-02-12_00-26-22](https://cloud.githubusercontent.com/assets/3697923/22858318/e5af53b6-f0b9-11e6-9ad6-344db1af5113.png)

I think that WheelSpeed changes because wheel is reset to 0 then to the former value when I switch between Scene Editor and GameView.

Maybe a fix could be by non resetting the wheel value when exiting Game View

**Comment by ilexp** [comment]
Thanks! This is definitely a bug - even though the wheel value should be zero when unavailable, the speed should not go crazy.

**Comment by ilexp** [comment]
Fixed. Release in progress. Check for package updates in about 30 minutes.
