### ISSUE TITLE
Add an option to set the rendering size of Game View windows

### ISSUE THREAD

**Issue by YMRYMR** [AdamsLair/duality#515]
### Summary

It would be useful to have an option to set the size of undocked view windows to see the real result when the external view is a camera.

### Analysis

- This feature would be useful to test different resolutions in the editor.
- It could be added in the view toolbar (see attached mockup).

### Attachments

![undockedviewsize](https://cloud.githubusercontent.com/assets/25836331/24510139/9f614f4e-1568-11e7-83e9-f4247cc1c88d.png)

**Comment by ilexp** [comment]
Sounds like a useful thing to have, though I would suggest to directly override the rendering size instead of the window size, as this would work both for docked and undocked windows. With this in mind, it's clearly a v3.0 branch issue as the required rendering changes are already available there.

**Comment by ilexp** [comment]
### Progress

- Investigated the rendering side of this and so far it looks like it should be doable without too much effort.
- Started working on this in the [develop-3.0-gameviewsize-wip](https://github.com/AdamsLair/duality/tree/develop-3.0-gameviewsize-wip) branch.

### Immediate ToDo

- Update textboxes based on window size changes.
- Validate textbox input and, when invalid, reset on losing focus.
- Apply textbox values to actual rendering output size.
  - Handle scale-up and scale-down separately
  - Scale-down: Just set the viewport size and center it in the available area.
  - Scale-up: Render to an internal RenderTarget and do a fitted blit into the actual view.
- Add a dropdown button to allow selecting a preset.
  - Game view size
  - Target size from DefaultUserData
- Serialize the output size setting to editor user data.

**Comment by ilexp** [comment]
### Progress

- Replaced the additional toolbar with occupying right-hand side space on the camera / editing toolbar that is unused in the Game View anyway.
- Textboxes now adjust to window size changes and parse values when entered.

### Immediate ToDo

- Validate textbox input and, when invalid, reset on losing focus.
- Apply textbox values to actual rendering output size.
  - Handle scale-up and scale-down separately
  - Scale-down: Just set the viewport size and center it in the available area.
  - Scale-up: Render to an internal RenderTarget and do a fitted blit into the actual view.
- Add a dropdown button to allow selecting a preset.
  - Game view size
  - Target size from DefaultUserData
- Serialize the output size setting to editor user data.
- Write lots of comments and XML docs for API, event if non-public where it makes sense.

**Comment by ilexp** [comment]
### Progress

- Target size textbox input validation, reset and overall behavior improved.
- Target size is now actually applied to the rendering output, using a RenderTarget for sizes bigger than the game view client area and rendering directly otherwise.
- Added a game view background, so there is a visual difference between an area that is not rendered to at all, and one that would be part of a game window with that size, but happens to be black.
- Added support for DualityApp, RenderSetup, Scene and Camera output render targets that are not the backbuffer, fixed internal viewport scaling bugs along the way.
- Fixed a RenderSetup bug that would produce an invalid Y coordinate axis in screen space rendering when image size and viewport size weren't equal.
- Implemented an input re-mapping for mouse coordinates when the game view window size is not equal to the simulated game window size.

### Immediate ToDo

- Add a button to reset to game view size. A dropdown menu allows to specify other presets:
  - Game view size
  - Target size from DefaultUserData
- Serialize the output size setting to editor user data.
- Write lots of comments and XML docs for API, event if non-public where it makes sense.

**Comment by ilexp** [comment]
### Progress

- Added a preset selection menu for rendering resolutions, including dynamic presets (game view, target size) and fixed presets (a set of common or useful resolutions).

### Immediate ToDo

- Serialize the output size setting to editor user data.
- Determine recently used resolutions.
- Add the three most recently used resolutions to the preset list.
- Write lots of comments and XML docs for API, event if non-public where it makes sense.
- Merge back to develop-3.0.

**Comment by ilexp** [comment]
### Progress

- Serialization of settings to EditorUserData.
- Recently used resolutions in the preset list dropdown.

### Immediate ToDo

- Write lots of comments and XML docs for API, event if non-public where it makes sense.
- Merge back to develop-3.0.

**Comment by ilexp** [comment]
Done.
