### ISSUE TITLE
Introduce a way to select the type of T in the editor

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#546]
When u are using the following class, the editor set for T "Single" by default. 
```CSharp
public class MyClass<T>
{
	public T Foo { get; set; }

	public T Bar { get; set; }
}
```
![](https://thumbs.gfycat.com/ImpartialOpulentGoldenretriever-size_restricted.gif)

So I can't use "string" or "boolean" as T.

It would be nice if the editor would bring up a dialogue where you can choose the type of T.
Like this:
![](http://i.imgur.com/mEXQ7ch.png)

**Comment by ilexp** [comment]
Hmm, this looks like a bug. My first guess would be that this could have something to do with the dynamic editor type adjustment feature which looks at the _actual_ type of a class instance, rather than its declared type in order to decide which editor to display. If that's the case, a potential fix would be to reset the selected type when the instance is removed and replaced with `null`.

To verify this, can you share the source code of `DynValue<T>` and the class that has the `ShieldHealth` property?

**Comment by ChristianGreiner** [comment]
Ohhh, sorry. My bad. I wasn't thinking. You can close this issue. 
I thought I declared just `DynValue<T>` in the class that has `ShieldHealth` which isn't possible. 
So everything works fine!

**Comment by ilexp** [comment]
Ah, alright 😄 Closing this.
