### ISSUE TITLE
Removing ScreenOverlay flag from Camera Visibility results in strange behaviour

### ISSUE THREAD

**Issue by FaithlessQ** [AdamsLair/duality#554]
### Summary

I wanted to deactivate the ScreenOverlay layer. So I deactivatet the ScreenOverlay flag from the viewing camera. This causes that SpriteRender Game Objects are now drawn two times if they are approximately at 0 < X < ScreenWidth, 0 < Y < ScreenHeight position: They will be drawn in their world postion and in their UI position, which is not the expected behaviour from developer perspective. I would expect no changes on the view for Game Objects which have no ScreenOverlay flag set. The sprite should be rendered only in its world position and not in the UI layer.

### How to reproduce [Bugs]

A simple scene with two game objects is needed to reprosduce:
* Create a new Duality project with a new screne
* Create a Camera with X, Y set to zero and Z to -500. VisibilityMask should be All.
* Create a Sprite using SpriteRenderer with a random graphic with X, Y, Z set to zero. Ensure VisbilityGroup of the Sprite is only Group0.
* Use the scene editor and use the created camera for viewing the scene, you should see the sprite in the center of the screen.
* Remove the ScreenOverlay flag from the VisiblitlyMask of the created Camera

==> The sprite can be seen two times now, one time for normal rendering in its world position in the center and one time for the UI rendering in its UI position which ist top left of the screen. The sprite may been have been clipped a bit. 

### Workaround [Bugs]

* For hiding the UI the other workaround which may used would be adjusting the Visibility of every UI-related Game Object to None. Therefore you need complete knowledge of you UI Game Objects instead of simple deactivating the UI on the camera.

### Analysis [Feature Requests]

I personally would prefer an adjustment of all affected Render classes (like SpriteRenderer) even if it is a strong breaking change. The behaviour as it is now, makes no sense, so I would consider it a bugfix.

So a change of the code within...

public virtual bool IsVisible(IDrawDevice device)

...on the Render classes would be possible solution.

### Attachments

This screenshots are using other coordninates than described above, but still are reproducing the mentioned behaviour:
![camera-all-visibilitymask](https://user-images.githubusercontent.com/30325942/28500433-93646d74-6fc8-11e7-9ffe-e9c4a7ef82c9.jpg)
![camera-allgroups-visibilitymask](https://user-images.githubusercontent.com/30325942/28500429-8e4190d8-6fc8-11e7-8c57-89fec2e59ed3.jpg)

**Comment by ilexp** [comment]
I have addressed this issue in a recent patch, but the way in which it was addressed may not fully reflect the intention of the original issue text, as this wouldn't have been in line with the existing design.

As far as the fix goes, it is no longer possible to accidentally create a camera setup that draws world-space objects a second time in screen space by unchecking the ScreenOverlay flag in the camera object. Instead, this flag will now be ignored as part of a cameras visibility mask, as it is considered a special flag that is to be set only on a per-pass basis - but at least setting it anyway does no longer do any harm. It was never intended to manually modify the ScreenOverlay flag on camera objects, so I chose stick to that rather than implementing a workaround that would add even more special behavior to that flag.

Going back to your original use case of disabling the rendering of screen overlay objects altogether, there are two ways to achieve this: One would be to temporarily set the visibility mask of the second render pass (screen overlay) to `None`, which would lead to not rendering any overlay objects. The other one, which is the one I'd recommend, is to designate one of the regular rendering groups as the "UI group" which you use for your overlay objects, and which you can disable and enable as needed just like any other group flag.

**Comment by FaithlessQ** [comment]
Thanks for fixing this issue and explaining a solution for hiding the UI elements. I will stick to your recommendation to do so.
