### ISSUE TITLE
'Edit Script' functionality

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#586]
### Summary

Add 'Edit Script' functionality which opens the source code (if available) of a component. If not possible show a error message that explains why (for instance a component of which you do not have the source code).

Might be possible in the way described here:
https://stackoverflow.com/questions/21785363/programatically-open-file-in-visual-studio?noredirect=1&lq=1

Will need some research to determine if this is a robust way of doing it (what will happen with multiple visual studio instances?). Possibly there are other ways of achieving this.

### Analysis

- Easier to find and open the source code for a component

**Comment by ilexp** [comment]
Not sure whether I think this is a good idea. Not because it wouldn't be convenient, but because I have doubts whether this can be implemented in a robust way without blowing up the effort / gain ratio.

> Will need some research to determine if this is a robust way of doing it (what will happen with multiple visual studio instances?). Possibly there are other ways of achieving this.

Opening Visual Studio directly doesn't sound like a great way to do this. People might use different simultaneously installed versions of Visual Studio, some might not even use Visual Studio at all, but prefer a different setup - point being: We should avoid making assumptions on what exact software someone uses to edit the code.

Also, I would imagine finding the right source code file to be not trivial in all cases. People can structure their code any way they want, and it might not even be C# code at all.

So.. yeah, I'm a bit skeptical, but ready to be proven wrong if a robust approach does exist for this.

**Comment by Barsonax** [comment]
Hmm it should be possible as Unity has similar functionality. Not sure if this is also possible with C# though in a reasonable way. It has to be robust too. The actual implementation is either simple or very hard probably and in the latter case we can just drop this issue. This will require some research.

The open source code button in duality currently simply opens the *.sln file. That won't work if the user does not have visual studio unless there is some other editor that works with *.sln files.

**Comment by ilexp** [comment]
> That won't work if the user does not have visual studio unless there is some other editor that works with *.sln files. This basically already assumes the user will use visual studio.

It doesn't really, because:

> The open source code button in duality currently simply opens the *.sln file.

The user will simply get the default choice he set up in their OS. What we do assume is that the user has some means to compile code into a .NET Assembly, which is simply a requirement for developing with Duality. It could be any Visual Studio version, MonoDevelop, VS Code, or whatever other editor comes along at some point.

> If multiple ide's have to be (fully) supported then alot of other things have to be changed too.

The currently implemented idea is that we simply don't support any IDE at all. It's none of Duality's business which IDE, build pipeline or other tooling the user prefers.

> Hmm it should be possible as Unity has similar functionality.

Unity also has a different approach to dealing with user code, as it replaces the user's choice build pipeline with its own and functions as a compiler environment itself. Duality, on the other hand, doesn't really care about code at all (beyond providing a default template) - it only cares about compiled Assemblies, which the user provides using whatever toolchain they like.

You're right that this will require some research and that there may be a way, but it might end up being too complicated or maintenance-heavy to outweigh the convenience gain.

**Comment by Barsonax** [comment]
Hmm unity forces you to keep the class name the same as the filename or it won't even recognize it so thats a bit cheaty.

Now it might be possible to get visual studio with the dte automation object to do what we want but seeing the amount of code and possible bugs with that I think we might as well drop the issue.
