### ISSUE TITLE
Improve Keyboard Handling in Object Reference Selection Dialog

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#605]
### Summary

The [Object Reference Selection Dialog](https://github.com/AdamsLair/duality/commit/bf11b157d5d0edaccc57862fbc447e4d6352e0de) can be opened, closed and filtered easily via keyboard only. One thing it can't do yet is change selection via up and down keys.

### Analysis

- Keyboard focus starts out being on the filter text box, which is good already.
- Up and down keys are currently not handled. Instead, they could be used to cycle selection through the currently visible list items, in order to allow doing keyboard-only selection after narrowing down options via filtering.

**Comment by BobGneu** [comment]
Up and down are already in place:  [duality/Source/Editor/DualityEditor/Forms/ObjectRefSelectionDialog.cs
](https://github.com/AdamsLair/duality/blob/9061c2b5da47e787a5ba1058907a821bd831e624/Source/Editor/DualityEditor/Forms/ObjectRefSelectionDialog.cs#L146-L163)
```c#
		private void TxtFilterInputOnKeyDown(object sender, KeyEventArgs keyEventArgs)
		{
			TreeNodeAdv tmp = null;

			if (keyEventArgs.KeyCode == Keys.Down)
			{
				tmp = this.objectReferenceListing.SelectedNode.NextNode;
			}
			else if (keyEventArgs.KeyCode == Keys.Up)
			{
				tmp = this.objectReferenceListing.SelectedNode.PreviousNode;
			}

			if (tmp != null)
			{
				this.objectReferenceListing.SelectedNode = tmp;
			}
		}
```
It automatically selects the top most element once you begin filtering and once you hit enter it accepts the form. Up and down use `PreviousNode` and `NextNode` to move through the listing as that appeared to behave in the context of a filtered listing.

**Comment by ilexp** [comment]
Huh, you're right. Not sure what I did when I tested this, but I somehow missed this. Closing this issue then, nice work!

**Comment by BobGneu** [comment]
One side note before closing this out, maybe it can be repurposed. Pressing down when filtering also includes moving the cursor in the filtered field. I don't particularly like that as it doesn't feel intuitive. Thoughts?

@ilexp

**Comment by ilexp** [comment]
> Pressing down when filtering also includes moving the cursor in the filtered field. I don't particularly like that as it doesn't feel intuitive. 

Not sure, what do you mean exactly?

**Comment by BobGneu** [comment]
When you open up the dialog and start filtering, press up or down and within the cuetextbox the text cursor will move. Pressing up moves the cursor to the left, and down moves the cursor to the right.

**Comment by ilexp** [comment]
Ah, makes sense. Seems like the up and down key presses aren't consumed, so they end up in regular text box input handling as well, and so selecting an item from the list via up / down will at the same time move the cursor too.

Re-Opening this for fixing this usability glitch.

**Comment by deanljohnson** [comment]
The bug where up/down is used in both the filtering field and list navigation is fixed in my branch [here](https://github.com/deanljohnson/duality/commit/a2740cfe8bd378f6a0124dc0be68c8620646b2cb). 

Now what I have noticed is that when the window first opens the filter field has focus and you can type right away. You cannot, however, start navigating with up/down right away **IF** the field was originally null. Once you have clicked on a list item, you can then use up/down for navigation while simultaneously typing in the filtering field. I think it'd be nice if immediately upon opening you could start hitting up/down to move through the list.

I looked into this further and found that if the reference was originally null when the dialog opens the `TxtFilterInputOnKeyDown` function throws a null reference when executing `this.objectReferenceListing.SelectedNode.NextNode`. It seems like what we could do is when the user presses down and there is no selected node, select the top node. When they press up with no selected node, select the bottom node. What do you all think?

**Comment by ilexp** [comment]
> The bug where up/down is used in both the filtering field and list navigation is fixed in my branch here.

> It seems like what we could do is when the user presses down and there is no selected node, select the top node. When they press up with no selected node, select the bottom node.

> It uses two extension methods I added to TreeViewAdv [here](https://github.com/deanljohnson/duality/commit/da4ad6146840b9b4ec8b725f95574feefe1a331f)

Sounds great 👍 Can you open a Pull Request on this, so we can merge your changes to master?

**Comment by deanljohnson** [comment]
Yes I can. However, I also have #607 implemented and have a PR issued for #606. Since these are all related to the same dialog, do you want me to make separate PRs for these or bundle them as one 'Object Ref Dialog Improvements' PR? Doesn't matter to me either way. If I do them separate I'll do them one at a time for you to review and will merge anything accepted into the next PR before issuing it.

**Comment by ilexp** [comment]
I'd say keep the already active PR open so we can conclude the review and merge, but bundle the others into a single PR. They seem small and related enough.

**Comment by ilexp** [comment]
Done by @deanljohnson.
