### ISSUE TITLE
Consider refactoring the default post build event in Plugin projects to a separate batch file

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#646]
### Summary

Currently all the code for this is in the post build event itself by default. Consider moving this to a separate batch file and call this batch file from the post build event.

### Analysis

- Easier to reuse this logic for multiple projects (like in pathfindax) leading to less duplication.
- Could be done by the developer himself but I believe having a good default to start from is important

**Comment by ilexp** [comment]
This is done differently in v2 and v3 - which one are you referring to? Assuming this is about v3, I like the current solution of using a custom msbuild copy step:

- It works on all platforms that can compile a csproj via msbuild or xbuild and does not rely on platform specific shell commands.
- It's defined in the project file / by the project itself, which knows best which files to copy.

So far I don't see the advantage of switching to a batch script, but a disadvantage due to being more maintenance heavy. What use cases do you have in mind?

**Comment by Barsonax** [comment]
Wasnt aware this is different in v3. How will v3 work with multiple duality plugin projects in a single solution? Will that msbuild step logic be shared or?

**Comment by ilexp** [comment]
Every project has its own (intermediate) build folder, but there is a single, shared build output folder, in which all binaries are aggregated. To do this, each project defines a copy step in its `csproj` using msbuild commands, which copy the projects output from its own build folder to the shared output. Here's an example for the [Project View](https://github.com/AdamsLair/duality/blob/f2f5eecf176dcf4be60d7d3d6377b69d4858b06c/Source/Plugins/EditorModules/ProjectView/ProjectView.Editor.csproj#L124) project.

**Comment by Barsonax** [comment]
Closing this as the situation in v3 is different
