### ISSUE TITLE
Add overload to IDrawDevice.AddVertices that accepts vertex indices

### ISSUE THREAD

**Issue by raycrasher** [AdamsLair/duality#676]
### Summary

I noticed that vertex indices are (kind of) supported in the engine now (```Duality.Drawing.VertexBuffer```, if I'm not mistaken). So it would be nice if IDrawDevice.AddVertices can also accept vertex indices.

Signature could be like this:

```C#
void AddVertices<T>(BatchInfo material, VertexMode vertexMode, T[] vertexBuffer, int[] indexBuffer) where T : struct, IVertexData;
```

This can be useful for lots of things like simple 3d objects, simpler tilemaps, as well as more optimized draw code.

**Comment by ilexp** [comment]
This is already supported with v3, it's just a slightly different API than you proposed 🙂 Instead of using an `AddVertices` overload, use [AddBatch](https://github.com/AdamsLair/duality/blob/39e0730d003c037f000c047d33d5714c91f94fa9/Source/Core/Duality/Drawing/IDrawDevice.cs#L115) and manually manage the `DrawBatch` you're submitting yourself. 

An example on how this is done can be found in the benchmarks sample, see [this block](https://github.com/AdamsLair/duality/blob/39e0730d003c037f000c047d33d5714c91f94fa9/Samples/Benchmarks/BenchmarkSetup/BenchmarkStaticMultiSpriteRenderer.cs#L135-L148). The sample still specifies vertices only, combined with a list of continuous ranges to draw from those vertices. However, [VertexBuffer can actually specify both vertices and indices](https://github.com/AdamsLair/duality/blob/39e0730d003c037f000c047d33d5714c91f94fa9/Source/Core/Duality/Drawing/VertexData/VertexBuffer.cs#L221), in which case [the vertex ranges will be ignored](https://github.com/AdamsLair/duality/blob/39e0730d003c037f000c047d33d5714c91f94fa9/Source/Platform/DefaultOpenTK/Backend/Graphics/GraphicsBackend.cs#L686-L707) and can be left out / specified as null. So you can specify a full vertex / index combo to be rendered, which is the equivalent of rendering a (sub-)mesh as you know it from more 3D oriented engines.

With the `AddBatch` approach, you will opt-out of the builtin vertex batching of DrawDevice, but still get the usual drawcall sorting and state change optimization. It's a way for you to handle all the details yourself if you want to, especially for cases like the ones you mentioned.

Closing this for now, but let me know if that's not what you had in mind.

**Comment by raycrasher** [comment]
Ok, thank you for the clarification. It seems more flexible when done your way, and I can always add extension methods to do what I originally proposed.
