### ISSUE TITLE
Duality package structure and nuspec is wrong

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#743]
### Summary

Duality now targets .NET 4.7.2 but in the lib folder there is still a net45 map:
![image](https://user-images.githubusercontent.com/19387223/62820788-bee2b700-bb69-11e9-8169-013998959a04.png)

I believe this should be changed to net472.

Also dependencies should be in a group (replace netstandard with netframework ofcourse):
```
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="System.Reflection.Emit.Lightweight" version="4.3.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```
And not like this:
```
    <dependencies>
      <dependency id="AdamsLair.Duality" version="3.1.3" />
      <dependency id="AdamsLair.DockPanelSuite" version="2.8.2" />
      <dependency id="AdamsLair.TreeViewAdv" version="1.7.7" />
      <dependency id="AdamsLair.WinForms" version="1.1.17" />
      <dependency id="AdamsLair.WinForms.PopupControl" version="1.0.1" />
      <dependency id="NuGet.Core" version="2.14.0" />
    </dependencies>
```

Pretty sure the current package structure will confuse nuget as it thinks its still a net45 package and not a net472 package. You also get tons of warnings in visual studio:
![image](https://user-images.githubusercontent.com/19387223/62820807-16812280-bb6a-11e9-8073-40c228dbf7ca.png)

I think we should fix this before proceeding with the nuget upgrade #740

**Comment by ilexp** [comment]
Yeah, the target framework in the package specs should be fixed. It's probably not critical, but important.

The ungrouped dependency specs are fine though [according to the docs](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element). Groups can be specified, but it's optional if they're the same across frameworks anyway. If we choose to do grouping anyway, we should probably go with a single group that doesn't specify a framework to indicate that it's the default.

**Comment by ilexp** [comment]
Note: This only applies to .NET Framework packages, not PCL packages. The PCL package folder would only change in the course of #573.

**Comment by Barsonax** [comment]
> The ungrouped dependency specs are fine though according to the docs.

When you generate a nuspec with `dotnet pack` it will always include the groups (even if there is just 1 group) with the corresponding targetframework. Nuget figures out the rest (such as compatibility).

The version without groups still works ofcourse but might get deprecated at some point.

**Comment by ilexp** [comment]
## ToDo

- Update all .NET Framework packages (editor, editor plugins, launcher, backend) to use `net472` target framework folders instead of `net45` target framework folders.
- Update the Duality Package Manager to favor `net472` instead of `net45`, both in the [manager target framework](https://github.com/AdamsLair/duality/blob/0f9d0fa75e54632abfe01e1be41dbbf6033f668e/Source/Editor/DualityEditor/PackageManagement/PackageManager.cs#L154) and for [framework-dependent content resolve](https://github.com/AdamsLair/duality/blob/0f9d0fa75e54632abfe01e1be41dbbf6033f668e/Source/Editor/DualityEditor/PackageManagement/PackageManager.cs#L1147-L1149).
- While at it, [fix this comment](https://github.com/AdamsLair/duality/blob/0f9d0fa75e54632abfe01e1be41dbbf6033f668e/Source/Editor/DualityEditor/PackageManagement/PackageManager.cs#L877-L878).
- Do a full local repository installation test.

**Comment by huffSamuel** [comment]
I implemented a fix for this on my fork of this repository. Since this is my first contribution to this repo, do you prefer doing an external review of my branch or is it preferred that I submit a PR and review through there?

**Comment by ilexp** [comment]
Sorry for the long delay, I'm pretty short on time lately - a Pull Request is probably the best way to go about this 🙂 Better visibility to project contributors for review, and also a good starting point for collaborating on your feature branch as the situation permits.
