### ISSUE TITLE
Copy task in AggregateUserPlugins.targets fails if no documentation file is generated

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#745]
### Summary

If no documentation file is generated the build will fail because its trying to copy a file that does not exists.

### How to reproduce

Create a new duality project and disable generating a documentation file and build the project

### Analysis
- Not generating a documentation file shouldnt fail the build
- Can be fixed by adding `Condition="Exists('$(OutputPath)$(AssemblyName).xml')"` to the copy task that copies the documentation file
- Might consider doing this for the pdb and dll files as well? You would get a build error anyway so no need to throw yet another error at the user.

**Comment by ilexp** [comment]
## Progress

- Fixed by adding a conditional to all output copy steps, so no additional build errors are generated when an output file is missing, or no XML docs are generated.
- Triggered a binary release for the editor.

Note that this only fixes the issue for projects that start off fresh, since the editor won't touch existing source folders / solutions. They'll have to be fixed manually.
