### ISSUE TITLE
Plugin class disappear on failed build

### ISSUE THREAD

**Issue by skrrtskrrtman** [AdamsLair/duality#765]
### Summary

I have encountered some strange behavior with Duality:
when you introduce a variable to a component class that is never set the build will succeed in Visual Studio but tell you of the error. When you remove the variable or the class altogether and rebuild Duality will reload and all of the plugins from the .csproj that contained the null object will be missing.

### How to reproduce
- create new class deriving from plugin
- add a var into the new class ie Vector2 target;
-  build and wait for Duality to reload
-  remove the previously added var or the class that contains it
- build and wait for Duality to reload
- attempt to add a component from the .csproj you have just done all this to
- notice the lack of any...

**Comment by ilexp** [comment]
Can you provide a specific code example that reproduces this behavior? I'm not sure I follow the repro steps so far. How does your class look like after each of these steps:

1. > add a var into the new class ie Vector2 target;
1. > remove the previously added var or the class that contains it

Does the build succeed after each step, or are there any errors?

> When you remove the variable or the class altogether and rebuild Duality will reload and all of the plugins from the .csproj that contained the null object will be missing.

When you remove the class, it would be expected behavior for it to be missing in Duality, since there no longer is anything that defined what a Component of that type is. Did I miss something?

**Comment by skrrtskrrtman** [comment]
I have tried several times to recreate the bug on a different project and cannot seem to do it sorry...
