### ISSUE TITLE
Fix xml doc warnings

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#804]
### Summary

I have noticed there are thousands of warnings in duality due to things like misformed xml documentation. For instance xml documentation where to parameters do not match the methid parameters. Consider fixing this as it really clutters the warning dialog and might lead to wrong documentation.

I noticed the following warnings:
- CS1591 (missing xml documentation), consider ignoring this warning with nowarn as this just generates so much warnings we will miss other more important warnings. Adding documentation to all public API is something we should do though but thats not gonna happen overnight.
- CS0419 (ambigious reference in cref)
- CS1572 (no mathing method parameter for param tag), needs to be fixed since its basically wrong documentation
- CS1573 (no matching param tag in xml), needs to be fixed since its basically wrong documentation
- CS1574 (cref could not be resolved), needs to be fixed since its basically wrong documentation

**Comment by ilexp** [comment]
I think most of those were ignored before - this was probably introduced due to the SDK project style change, [see here](https://github.com/AdamsLair/duality/blob/8455bd9649861e61787c24e56fe5447bafba084b/Source/Core/Duality/Duality.csproj#L25) for the previous warning setup for reference.

At least CS1591 and CS0419 can be safely ignored with no harm done, depends for the others. Not suddenly drowning in docs warnings, causing people to miss other, more important warnings, should be a priority though.

**Comment by Barsonax** [comment]
Ah they were defined in the csproj itself? Missed that when doing the migration.. I think its better to move these to the `Directory.Build.props` file though. I will add CS0419 as well.
