### ISSUE TITLE
Rectangular tilesets are incorrectly displayed

### ISSUE THREAD

**Issue by Seti-0** [AdamsLair/duality#818]
### Summary

In the duality tilemaps plugin, when using a Tileset with a margin and source tiles that are not square, there will be thin vertical holes in the rendered Tilemap.

### How to reproduce

 - Create a Tileset with source tiles that aren't square, and a margin that isn't zero. 
 - Render a Tilemap with a TilemapRenderer and using the Tileset.

For a black camera background, the holes will appear as black lines.

I'm not sure if they will show for all camera distances, but I've never seen them not show.

### Analysis

The holes are present in the output from TilesetCompiler.Compile(...), and looked like missing left/right margins of width 1. (I never checked with thicker margins)

In TilesetCompiler.cs, under TilesetCompiler.FillTileSpacing(...), the function iterates over the width of the target tile size for each margin.

Switching the width to height for the left and right margins seemed to fix the issue. (Tested on a local build of Duality.)

### Attachments

- [Screenshot](https://i.imgur.com/SioOgPU.png)

**Comment by ilexp** [comment]
Just adding some info from the chat and links for convenience, the two lines in question are:

- https://github.com/AdamsLair/duality/blob/1036cc01b64ccd11003559b7f835aa7d0f864aa6/Source/Plugins/Tilemaps/Core/Tilesets/TilesetCompiler.cs#L620
- https://github.com/AdamsLair/duality/blob/1036cc01b64ccd11003559b7f835aa7d0f864aa6/Source/Plugins/Tilemaps/Core/Tilesets/TilesetCompiler.cs#L631

There may be a typo and what should be iterated on is actually `targetTileSize.Y`, not `.X`.

-------

**Important note:** In order to release this for the current v3.x Duality versions despite being in the middle of transitioning to v4.0 on `master`, any PRs addressing this issue should be made to merge into the `archive/v3.x` branch. 

-------

Additional note for @AdamsLair/duality-core maintainers: The release can then be done by doing the regular package version update script on that branch, followed by merging it into `release`. The change can then be merged or cherry-picked to `master` to retain it when moving to v4.0.

**Comment by ilexp** [comment]
> Switching the width to height for the left and right margins seemed to fix the issue. (Tested on a local build of Duality.)

@Seti-0 Since you already seem to have a local fix, do you want to pick up this issue and contribute it with a Pull Request?

**Comment by Seti-0** [comment]
I made a PR :)

I've no experience with git/github, so let me know if there is something I could/should be doing differently.

**Comment by SirePi** [comment]
Thanks for the PR. Will be out as soon as we figure out what happened :) Closing this in the meantime
