### ISSUE TITLE
Consider changing code style to allow var when the type is apparent

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#854]
### Summary

We currently have a editorconfig with some style rules set. Consider changing these to make the code more readable, shorter etc.

NOTE: these changes do not change the semantics of the code. For newer C# features that might involve style changes we also have a different issue https://github.com/AdamsLair/duality/issues/742

### Analysis

- We could make it so that when the type is apparent theres no need to use a explicit type. A type is apparent when its clear what the type is just by reading the source code regardless how things are named or what defaults the language uses. A common example of this is when creating a new variable and using a constructor to assign it:
```
# IDE0008: Use explicit type
csharp_style_var_when_type_is_apparent = true:suggestion

# IDE0008: Use explicit type
csharp_style_var_for_built_in_types = false:error
```

**Comment by Barsonax** [comment]
done in #863

**Comment by ilexp** [comment]
I'm re-opening this because it seems that this change leads to the IDE actively promoting inconsistencies in some cases. There are two classes of issues I've seen in the codebase recently:

## Inconsistent var / explicit combos

There are a lot of cases where the IDE will now suggest to use `var` in one line, but an explicit type in the next, which will turn local variable initialization blocks into an inconsistent mix of both. Either the entire block should use `var`, or the entire block should be explicit, but not both.

![devenv_cy4mZfngEn](https://user-images.githubusercontent.com/14859411/87716054-8eaa8c00-c7ae-11ea-85af-8aec80338845.png)

![devenv_hw3QSLrmyw](https://user-images.githubusercontent.com/14859411/87716057-8f432280-c7ae-11ea-9405-27524712696b.png)

![devenv_YanN78JPPc](https://user-images.githubusercontent.com/14859411/87716058-8fdbb900-c7ae-11ea-9b88-0b4d8b2f2c14.png)

![devenv_mR3voKfLsl](https://user-images.githubusercontent.com/14859411/87716059-8fdbb900-c7ae-11ea-89ab-af7c86eb1f67.png)

## Suggesting to use var when the type is actually not apparent

In some cases, the IDE will suggest using `var` even though the actual type is implementation dependent and technically, a member lookup is required to determine it.

![devenv_2yYcFT7BaQ](https://user-images.githubusercontent.com/14859411/87716446-28723900-c7af-11ea-9b53-1cae89bd7b41.png)

![devenv_phSOxN69AA](https://user-images.githubusercontent.com/14859411/87716447-28723900-c7af-11ea-90b7-46d110e376f6.png)

------

To address this, I'd like to revert the linked editor config change and go back to preferring explicit types everywhere. I'm totally okay with manually deviating from this in places where it makes sense, but I don't think the IDE should continue to generally suggest this - seeing this effect, I think the change can easily cause more trouble than it's worth 😐

**Comment by Barsonax** [comment]
It shouldn't suggest var in these cases, there's some other setting doing this.

**Comment by Barsonax** [comment]
![image](https://user-images.githubusercontent.com/19387223/87719524-c7992f80-c7b3-11ea-877a-15070692b322.png)
Not sure what visual studio is doing here but this doesnt make any sense why it suggest var in one case but not in the other similar case?

**Comment by ilexp** [comment]
> EDIT: @ilexp better just revert this. Its not doing what I suspected it to do but missed these edge cases during the tests...

Done. Closing this for now until the topic comes up again, feel free to re-open as needed.
